### ISSUE TITLE
Potential memory leak with DefaultRSocketClient not READY

### ISSUE THREAD

**Issue by a701440** [rsocket/rsocket-java#1022]
RSocket version 1.1.0

I am still investigating the issue, but it appears that there may be a memory leak with DefaultRSocketClient subscribers array 
(ResolvingOperator.subscribers). When rsocket operations like "fireAndForget" or "requestResponse" are issued they are added to the array of subscribers (I assume waiting for the READY state). If these operations also use a timeout and are cancelled they don't seem to be removed from the subscribers array. If the client does not reach the READY state quickly (networking issues, etc) it's possible to have a pile-ip of these subscribers in the array.

<img width="694" alt="heapdump" src="https://user-images.githubusercontent.com/3812276/127882781-703df49c-470f-4f65-a5ce-708a1f77564d.png">

**Comment by OlegDokuka** [comment]
Hey, @a701440! 

You check that issue with 1.1.1 please?

Thanks

**Comment by a701440** [comment]
So far I could not reproduce in a test on both 1.1.0 and 1.1.1. 

I think ResolvingOperator.add and ResolvingOperator.remove are not atomic though.
They take a copy of the subscribers array. Only swap ref is atomic, but not the modifications.

So it's likely that there will be array corruption under load?

**Comment by OlegDokuka** [comment]
we had a bug in 1.1.0 related to the `DefaultRSocketClient` impl but it was fixed in 1.1.1, thus, I can only recommend migrating to 1.1.1 and let us know if this issue is still happening at your prod runtime

**Comment by OlegDokuka** [comment]
a bit of references -> https://github.com/rsocket/rsocket-java/pull/1008/files#diff-dc96112bec654b2fc960d08a7ca32d9d5094996ed327737679dbbcf59ce74b98L156

**Comment by OlegDokuka** [comment]
closing since seems to be fixed
