### ISSUE TITLE
Any plan for integration with opentracing?

### ISSUE THREAD

**Issue by AtticusLv** [rsocket/rsocket-java#1030]
As RSocket is supporting openzipkin b3 propagation, is opentracing tech stack on the supported list of RSocket😺

**Comment by spencergibb** [comment]
Probably a more general extension request not specific to java. https://github.com/rsocket/rsocket/blob/master/Extensions/Tracing-Zipkin.md

**Comment by making** [comment]
@AtticusLv [The OpenTracing propagation format specification](https://github.com/opentracing/specification/blob/master/rfc/trace_identifiers.md) remains in the "Draft" state, and OpenTracing has been merged into OpenTelemetry and is no longer active.
I don't think this format will be supported in the future.
Maybe, you can request [W3C Trace Context](https://www.w3.org/TR/trace-context/) support instead.

**Comment by OlegDokuka** [comment]
Is not it something supported by so called spring-observability in future? I expected we going to integrate with that once that project is in the preview stage.

**Comment by AtticusLv** [comment]
Thanks for the reply. We'll fulfill opentracing just like this https://github.com/rsocket/rsocket/blob/master/Extensions/Tracing-Zipkin.md . 

Ticket is closed
