### ISSUE TITLE
SendUtils onDiscard handler class cast exception

### ISSUE THREAD

**Issue by Svenskunganka** [rsocket/rsocket-java#1077]
I'm using RSocket Java with Spring Webflux and RSocket JS in the front-end, using `REQUEST_STREAM` with an infinite Kafka source. The returned Flux receives quite a lot of small messages and does quite a bit of filtering and buffering. [The relevant code in `SendUtils`](https://github.com/rsocket/rsocket-java/blob/e31038f04e8bfc7b9c3a9a2b3a12fd578ed02a40/rsocket-core/src/main/java/io/rsocket/core/SendUtils.java#L41-L51) does an unchecked cast of each discarded object to a `ReferenceCounted` which seems to throw a class cast exception that is caught and ignored.  
The problem is that due to the sheer amount of objects being discarded (due to filtering and discarded buffers on disconnect), this uses up a substantial amount of CPU resources looking at the profiler.

![profiler](https://user-images.githubusercontent.com/2657513/199223616-fb5f8086-566b-4554-b57c-af3605ce1b62.png)

The returned Fluxes are scheduled on `Schedulers.boundedElastic()`, and for some reason entire threads are started up just for this exception:
![flamegraph](https://user-images.githubusercontent.com/2657513/199225004-be4db466-4e3d-4ad7-8da6-a42274009945.png)

## Expected Behavior
Not use up so much CPU resources

## Actual Behavior
Uses a lot of CPU resources

## Possible Solution
Not exactly sure, but perhaps an `instanceof` check:
```java
if (data instanceof ReferenceCounted) ((ReferenceCounted) data).release();
```

## Your Environment

* RSocket version(s) used: rsocket-core:1.1.3, rsocket-transport-netty:1.1.3
* Other relevant libraries versions (eg. `netty`, ...): Spring Webflux 5.3.23
* Platform (eg. JVM version (`javar -version`) or Node version (`node --version`)): 17
* OS and version (eg `uname -a`): Happens on all tested platforms (Debian, Mac)

**Comment by OlegDokuka** [comment]
@Svenskunganka! Sounds relevant! 

Feel free to contribute if you see the direct solution, otherwise, I will investigate it!

Best,
Oleh

**Comment by Svenskunganka** [comment]
Hi Oleh!

If my possible solution is acceptable I can definitely contribute it! But if you perhaps know of another way this could be solved without needing to perform an `instanceof` check for every discarded object that might be a better route to explore.  
From my limited experience the only thing I can think of is using e.g `Mono.using()`/`Flux.using()` when creating a `Payload`.

```java
input.flatMap(bytes -> Mono.using(
    () -> ByteBufPayload.create(bytes),
    data -> ...,
    Payload::release
));
```

Kind regards,
Tom

**Comment by luczus** [comment]
Hi Oleh, @Svenskunganka!

I created #1079 with a fix.
Please let me know what you think about these changes.

Best 
Lukasz

**Comment by tukez** [comment]
I noticed the same problem and in my case at least the offending instance is of type org.springframework.core.io.buffer.NettyDataBuffer which holds a ByteBuf. Should the inner ByteBuf be released? That is not possible (other than reflection) in rsocket-java though?

**Comment by kmccarp** [comment]
@OlegDokuka are there any plans to integrate the changes made by @luczus? This is heavily polluting our logs.
