### ISSUE TITLE
Upgrade Framing to Spec 1.0

### ISSUE THREAD

**Issue by benjchristensen** [rsocket/rsocket-java#220]
The 0.5 branch is currently compliant with spec 0.1. v0.2 of the spec has landed, and resumability is about to land (maybe making it 0.3?). This will make the spec ready to hit v1 within the next month hopefully. 

I have engineering time on my team to tackle upgrading the framing of the Java implementation, and ensuring Java/C++ interop over the coming weeks (and need this working in that time frame for something we're doing).

Any issues with us taking on this work? Do you want us to target the 0.5 branch, or something else? At what point do we call it "master" or "1.x"?

**Comment by NiteshKant** [comment]
@benjchristensen sure! We should target 0.5.x as that is where all development is happening.

\cc @stevegury @robertroeser

**Comment by benjchristensen** [comment]
Sounds good. We will keep you updated as we make progress. Thanks.

**Comment by benjchristensen** [comment]
We plan to start on this soon as the spec is nearing completion and we're working on reactivesocket-cpp right now.

**Comment by benjchristensen** [comment]
Is it essential for the code to remain backwards compatible (server taking older frames), or can it be a breaking change where both client and server deployments need to be upgraded?

I assume backwards compatibility is needed, but it would be easier and cleaner to break.

**Comment by robertroeser** [comment]
I think a clean break would be ok - no need to add tech debt right now.

**Comment by benjchristensen** [comment]
Great, that makes this far simpler. Thanks Robert.

**Comment by benjchristensen** [comment]
Since we are going to be in flux for a bit, we are going to do this on a separate branch while we submit, review, and merge all the diffs for framing. So we don't break everyone on 0.5.x during that time, I have created 1.0.x for all of that right now. 

Any issues with us targeting 1.0 Release Candidate once we get the framing nailed down? Or would you prefer something like 0.6?

**Comment by benjchristensen** [comment]
This relates to https://github.com/ReactiveSocket/reactivesocket/issues/143 where we are approaching v1.0 of the spec. We will call it 1.0 Final once we prove the implementation in both Java and C++. 

The Java and C++ 1.0 versions will happen whenever they consider themselves ready, not related to us considering the spec final at 1.0

**Comment by robertroeser** [comment]
We should probably add back in the TCK before we start making release candidates? Maybe version 0.6 after the framing stuff is added?

**Comment by lexs** [comment]
https://github.com/ReactiveSocket/reactivesocket-java/tree/1.0.x now contains mostly an up-to-date impl of the 1.0 spec. The bit missing is handling of the NEXT bit of payloads, both sending it and not handing data of to onNext() if it's not present.

I'll spend the rest of this date writing tests to verify that the wire format is according to spec, but I agree having the TCK would be nice before we release anything. I believe somebody from Facebook was going to start working on the TCK, @benjchristensen ?

**Comment by lexs** [comment]
@somasun filed https://github.com/ReactiveSocket/reactivesocket-java/issues/244 for TCK.

**Comment by yschimke** [comment]
Can this be closed?
