### ISSUE TITLE
Add infer @Nullable checks to CI build

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-java#286]
Should we consider adopting some of the Square practices here?

https://medium.com/square-corner-blog/rolling-out-nullable-42dd823fbd89
https://medium.com/square-corner-blog/non-null-is-the-default-58ffc0bb9111

@Nullable, and @ParametersAreNonnullByDefault

**Comment by lexs** [comment]
Strongly in favor. Internally we (Facebook) have our entire codebase be non-null by default using https://github.com/facebook/infer to force `@Nullable` where it's needed.

**Comment by robertroeser** [comment]
@lexs Does infer work with the javax.annotation.Nullable? If it did that would be great because we wouldn't have to have a dependency on Guava.

There appears to be a gradle plugin for this:
https://github.com/uber-common/infer-plugin

This seems like a good idea to add this to the build.

**Comment by yschimke** [comment]
I'm trying this out at the moment

**Comment by yschimke** [comment]
The plugin seems to have version incompatibilities with newer gradle versions, but infer docs work fine externally for now.

https://github.com/rsocket/rsocket-java/pull/288
