### ISSUE TITLE
Minimal developer documentation setup

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-java#301]
I'd settle for just starting with the code style to use by default.

I believe its sort of close to Intellij default java code style.

cc @robertroeser @rdegnan @tmontgomery

**Comment by yschimke** [comment]
@robertroeser @rdegnan @tmontgomery What do you each think our code style is?

**Comment by rroeserr** [comment]
What about using a plugin to do this? 
https://github.com/diffplug/spotless
https://github.com/diffplug/spotless/tree/master/plugin-gradle
https://github.com/google/google-java-format

**Comment by robertroeser** [comment]
What about using a plugin to do this?
https://github.com/diffplug/spotless
https://github.com/diffplug/spotless/tree/master/plugin-gradle

**Comment by yschimke** [comment]
@robertroeser perfect, but it still leaves open the question what our format is?

**Comment by robertroeser** [comment]
I guess it supports this:
https://github.com/google/google-java-format

Makes it easy.

**Comment by yschimke** [comment]
Yep, let's go with that https://plugins.jetbrains.com/plugin/8527-google-java-format

**Comment by yschimke** [comment]
https://github.com/rsocket/rsocket-java/pull/303/files

**Comment by yschimke** [comment]
I formatted a few files in the PR above, both with the gradlew command and the intellij plugin.  both are working.

**Comment by yschimke** [comment]
Reformatting the rest of the codebase https://github.com/rsocket/rsocket-java/pull/305

**Comment by robertroeser** [comment]
Merged the changes for formatting.
