### ISSUE TITLE
upgrade codebase to reactor-core 3.1.x

### ISSUE THREAD

**Issue by tsachev** [rsocket/rsocket-java#304]
reactor core 3.1.0.RELEASE and reactor-netty 0.7.0.RELEASE are scheduled for release by the end of this month. I plan to update my code base to use them, but there are breaking changes in reactor-core api which does not allow me to just force the new version if I depend on rsocket too.
For  example `Mono.then(Supplier)` is gone in favor of `Mono.map(Supplier)` etc. 

Would you consider upgrade before releasing rsocket 1.0?

**Comment by yschimke** [comment]
+1

That makes sense to me.

**Comment by yschimke** [comment]
@tsachev Is there a published RC of reactor-netty?  It would be good to test the changes here before 0.7.0 is released.

**Comment by tsachev** [comment]
just checked with the reactor devs on their gitter. It seems that they ensured that reactor-netty `0.6.4` is compatible with the new reactor-core `3.1` too. If its not you should raise issue against reactor-netty.

**Comment by yschimke** [comment]
@tsachev testing the upgrade here https://github.com/rsocket/rsocket-java/pull/323

**Comment by yschimke** [comment]
@tsachev Release date for 3.1? "it might shift toward end of August" 😑

**Comment by yschimke** [comment]
https://github.com/rsocket/rsocket-java/pull/400
