### ISSUE TITLE
Question: what is the most viable RPC binding?

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-java#369]
Using rsocket-java, I'm missing something like Retrofit, or thrift idls to java Interface generation.  Retrofit is unfortunately a fudge because its so web centric.

What is our story here?

**Comment by yschimke** [comment]
Thrift is a viable option here

**Comment by robertroeser** [comment]
@yschimke starting to work on something - https://github.com/netifi/proteus-java
Should be in bintray later today.
