### ISSUE TITLE
Remove spectator rsocket, add micrometer rsocket

### ISSUE THREAD

**Issue by robertroeser** [rsocket/rsocket-java#434]
Micrometer is a generic way to monitor things in Java. We should re-implement the Spectator RSocket to Micrometer
http://micrometer.io/

**Comment by yschimke** [comment]
Can these live externally? If we want them as modules in rsocket-java builds, what is our line for things that should be modules vs external libraries?

**Comment by robertroeser** [comment]
We could make a rsocket-java-ext project for stuff like this, but then it's cumbersome to update and test them. They are seperate jars so it won't really affect people using rsocket. I it's ok to leave them here.

**Comment by yschimke** [comment]
I'm ok with either for now

**Comment by smaldini** [comment]
Strongly in favor of this (Biased tho). @jkschneider is pretty proactive if you need some advices too. For the context, we will introduce micrometer as an opt. dep in the next major Netty version. There also are plans for OoB support of reactor fluxes/mono we are evaluating.
