### ISSUE TITLE
Question: How do you detect that the rsocket on the other end has been closed?

### ISSUE THREAD

**Issue by natronjb** [rsocket/rsocket-java#447]
I've got a little sample app that shoots some data back and forth and everything is working just dandy.  However, I then close one rsocket, and I was hoping to get some sort of indication that it was closed on the other end.  I'd expect that the far end would stop seeing keepalives and that would indicate that the near side is dead, and that the consumer I attached to onClose() via the subscribe() call would execute.  But alas, nothing appears to happen.

**Comment by robertroeser** [comment]
Yes the keep alives should do this. How long did you wait?  I'll take a look at this.

**Comment by natronjb** [comment]
I only waited three seconds.  Maybe that's not long enough?  Let me try waiting longer.  Maybe I'm just too impatient.  :-)

FWIW, here's the first line of my accept() function inside my SocketAcceptor:

sendingSocket.onClose().subscribe(v -> System.out.println(" -- detected close -- "));

I'm a little new to the Mono/Flux stuff, but it seems like that is correct...

**Comment by natronjb** [comment]
Just tried waiting 100 seconds and nothing happened.  Is there something I have to do to enable keepalives?

**Comment by robertroeser** [comment]
I don't necessarily recommend something so aggressive for prod, but for testing you can set something like
```
RSocket rSocket =
          RSocketFactory
.connect()
.keepAlive(Duration.ofSeconds(1), Duration.ofSeconds(5), 1)
...
```
let me know if that works.

**Comment by natronjb** [comment]
I'll give that a shot.  I am actually trying to detect that a client disconnected from the server side.  I don't see a similar hook for setting up keepalives on new incoming connections.  I see in the protocol definition that the client initiating keepalives is a 'MUST', but the server initiating keepalives is a 'MAY', so perhaps that's not implemented in the current version?  If so, it's not a huge deal for me - I'm going to have some other protocol aimed at the server that I can use to detect that the far end is gone.  Or perhaps this is an opportunity for me to contribute to the project.  :-)

**Comment by mostroverkhov** [comment]
`Mono<Void>` of `onClose()` never emits `onNext` signals - only `onComplete`, so you probably should try three args `subscribe({onNext}, {onError}, {onComplete})`, and listen for {onComplete}. How do you detect that transport is alive after close? Do you see server server receives client initiated `KeepAlive` frames after close?

**Comment by natronjb** [comment]
Ok I'll look for onComplete.

After I close the client rsocket, I stop seeing traffic (I've inserted a netty handler that logs incoming/outgoing packets and it stops printing things once the client rsocket is closed).

**Comment by natronjb** [comment]
That did it!  The onComplete from the subscribe fired.  Thanks for your help!
