### ISSUE TITLE
Question: what's the 'best' way to interact with the netty channel pipeline?

### ISSUE THREAD

**Issue by natronjb** [rsocket/rsocket-java#448]
Using the TcpServer and TcpClient builder options, I've been able to grab the pipeline from inside the afterChannelInit function.  Is that the right place to go about mucking around with handlers in the pipeline?  Is it possible/wise to try and inject the rsocket netty handlers into a pipeline that I establish outside of the RSocketFactory infrastructure?  Or would I be setting myself up for a world of pain.  :-)

I *may* need to intercept some initial handshake messages that determine if I'm going to try and setup encryption/compression, and I want to make sure I do that with maximum smartness.

**Comment by natronjb** [comment]
Along similar lines, is it possible to influence the EventExecutorGroup to which the rsocket netty handlers are assigned?

**Comment by robertroeser** [comment]
You can set the event group in the reactor-netty options. There is a plugin in reactor-core you assign it's scheduler to the same executor. You can run RSocket over TLS using this options.

If you doing some other kind of encryption you could insert a handler after RSocketLengthCodec so you can are encrypting/decrypting Frames.  RSocket has a DuplexConnector plugin. The other option is to create an RSocket plugin that encrypts and decrypts the payloads. RSocket, and the DuplexConnection are composable so I would just do something like that.

Plugins
https://github.com/rsocket/rsocket-java/blob/1.0.x/rsocket-core/src/main/java/io/rsocket/plugins/Plugins.jav

**Comment by natronjb** [comment]
Ok.  I see where I can specify the eventLoopGroup (via the TcpServer.Builder and TcpClient.Builder).

However, I'm totally not following you regarding the DuplexConnector and RSocket plugins.  I see where I can register interceptors via the Plugins object.  But then what I'm I supposed to do with them?  Looks like I can interpose my own RSockets and DuplexConnections.  I see these interceptors fire a handful of times when I first connect a client to a server, but then they don't fire anymore.

Regarding the LengthCodec, I see that handler in the pipeline from inside my own netty handler that I added to the pipeline inside afterChannelInit().  But the LengthCodec isn't there inside afterChannelInit().  Is there a hook that gets called after the rsocket code is done adding stuff to the pipeline?  Or I suppose I can always keep my own handler at the front, then when I first get data, look at the whole pipeline, and add whatever I feel like adding then, then have that handler remove itself.  I've played games like that in the past.

**Comment by robertroeser** [comment]
Depends what you want to do. If you want to use the transport layer for encryption use Netty. If you want this to be model at the application protocol layer you'd use RSocket. If you use a DuplexConnection you wrap the provided DuplexConnection so when send and receive are called you could compress and ecrypt the frames, or you could wrap the RSocket then the request methods are called.

**Comment by natronjb** [comment]
Ok.  Thanks.
