### ISSUE TITLE
publish to maven central

### ISSUE THREAD

**Issue by tsachev** [rsocket/rsocket-java#463]
I see some releases going into jcenter,
https://jcenter.bintray.com/io/rsocket/rsocket-core/

Do you plan to publish them to maven central too? There are only some old releases with groupId io.reactivesocket there. But they do not work for me.

**Comment by yschimke** [comment]
I think this just involves completing more information in our poms to meet the requirements

http://central.sonatype.org/pages/requirements.html

Then enabling here https://bintray.com/rsocket-admin/RSocket/rsocket-java#central

**Comment by yschimke** [comment]
I think it's been low priority, since gradle moved away from the centralised model.  And you can always add extra repositories in maven.

cc @robertroeser

**Comment by robertroeser** [comment]
tried publishing to maven central in the bintray console and got an error. Maybe there is some missing setup?

**Comment by yschimke** [comment]
There is an Authentication failed message which confused me, but I didn't think we passed the minimum requirements

http://central.sonatype.org/pages/requirements.html

**Comment by robertroeser** [comment]
So we need to add more information into our POM then?

**Comment by smaldini** [comment]
We can setup the pipeline if you want, also we already have an authorization for our group id if you want to leverage it.

**Comment by robertroeser** [comment]
@smaldini that would be great if you could do that - then I can try to get his maven central again.

**Comment by yschimke** [comment]
@smaldini @robertroeser Does that imply a module rename to io.projectreactor:rsocket-java?  No opinion from me, just checking.

**Comment by ktoso** [comment]
Getting permissions really isn't all that hard, just opening a ticket at sonatype's jira so I don't think someone-having-permissions-somewhere already should be the deciding factor where a project is released :-)

Some helpful links: 
- http://www.sonatype.org/nexus/2015/01/08/deploy-to-maven-central-repository/
- http://central.sonatype.org/pages/ossrh-guide.html ("applying for access" etc)
- random example of such ticket with asking for permissions: https://issues.sonatype.org/browse/OSSRH-12425?

**Comment by robertroeser** [comment]
@yschimke No idea - was just thought things was some process we could use
@ktoso thanks for the links, and will look into this

**Comment by smaldini** [comment]
Let me know how it turns out @robertroeser and if you still need a build from us.

**Comment by benjchristensen** [comment]
I have the Sonatype account setup for RSocket already. Since my schedule sucks right now I can pass off credentials to someone so I'm not a blocker.

**Comment by yschimke** [comment]
I’ve got creds as well. Their is a checkbox when you log in. I think first step is to add all the required details to the Pom. I can try enabling after that. I joined else I can try this weekend.

**Comment by benjchristensen** [comment]
So, I did this process already with Sonatype. Here is the issue: https://issues.sonatype.org/browse/OSSRH-32294

**Comment by benjchristensen** [comment]
Looks like maybe we just never finished the process?

**Comment by smaldini** [comment]
Given the right build it will then be able to push or with the key signature you can manually upload to codehaus. We automate this process in a Bamboo-to-jfrog-to-codehaus automatic signing process but for the time being you can maybe sign locally.

**Comment by robertroeser** [comment]
https://benlimmer.com/2014/01/04/automatically-publish-to-sonatype-with-gradle-and-travis-ci/

Looks like you can do this with Travis?

**Comment by tsachev** [comment]
I see 0.11.0 is now in central but poms do not have dependency section? Why is that? For example I would expect `rsocket-transport-netty` to have dependency on `rsocket-core` and `reactor-netty`.

**Comment by mostroverkhov** [comment]
@tsachev see https://github.com/rsocket/rsocket-java/issues/498
