### ISSUE TITLE
Add support for rejecting setup

### ISSUE THREAD

**Issue by tsachev** [rsocket/rsocket-java#464]
According to the protocol server can decide to reject a setup (https://github.com/rsocket/rsocket/blob/master/Protocol.md#negotiation) which should result in sending an error to the client (and closing the connection?).

Currently its not possible to do so.
One use case that comes to mind is that the server currently does not support the media types of data/metadata send by the client.

I would expect if the acceptor returns `Mono.error` then REJECTED_SETUP should be send to the client (on zero connection).

I it would be ok if I could achieve the above with a server plugin, but I do not see how a can send messages to Stream 0 from there.

Also these seems kind of related to #311

**Comment by mostroverkhov** [comment]
I think It is possible with `DuplexConnectionInterceptor` on 0 connection. Peek into `source.receive()` with `doOnNext()` and check Setup frame contents, and in case of discrepancy send Error frame manually, then close connection (that's what Server does on RSocket version mismatch)
```java
conn.sendOne(Frame.Error.from(0, error))
              .then(conn.close());
```

**Comment by kacper-emersoft** [comment]
@mostroverkhov as per discussion in #743 I have tried to similar solution and seems it is not working as expected
```
public DuplexConnection apply(Type type, DuplexConnection duplexConnection) {
                ByteBuf byteBuf = ErrorFrameFlyweight.encode(ByteBufAllocator.DEFAULT, 0, new RejectedException("any reason"));
                duplexConnection.sendOne(byteBuf);
                duplexConnection.dispose();
                return duplexConnection;
}
```
Connection is closed but client doesn't receive error. He receives connection closed exception but only after requesting a payload exchange. I would expect to receive error on client side immediately before (or within) setup phase.

**Comment by mostroverkhov** [comment]
@kacper-emersoft Looks like this was fixed few years ago - server acceptor may return `Mono.error` which will close RSocket with REJECTED_SETUP error frame.
