### ISSUE TITLE
State of the project?

### ISSUE THREAD

**Issue by Petikoch** [rsocket/rsocket-java#469]
Hi,

what's the state of the project? 
Is it already ready to use "in production"?  
Is there a roadmap? 

Thank you for your time & best regards,
Peti

**Comment by yschimke** [comment]
Working, used in production internally inside a small number of large companies.  Actively developed and maintained, i.e. Any bugs you find when using, please report.

There is at least one commercial company behind it https://www.netifi.com/

Hopefully more soon, e.g. https://www.slideshare.net/Pivotal/project-reactor-now-and-tomorrow "Exploring RSocket"

There are working public examples you can use and support tooling (curl like CLI etc)

JS -> Java Websockets - http://rsocket-demo.herokuapp.com/
CLI - brew install yschimke/tap/rsocket-cli

**Comment by Petikoch** [comment]
Thank you very much @yschimke for the details. 

I'm the leader of a local meetup group exploring mostly "reactive stuff" on the JVM. We're currently looking at Spring WebFlux (https://github.com/ReactiveMeetupLucerne/SpringWebFluxWithSpringBoot2.0) and I think we are going to check out RSocket soon, too. 

Have a good time and best regards,
Peti
