### ISSUE TITLE
rsocket-transport-netty with SSL

### ISSUE THREAD

**Issue by krisskross** [rsocket/rsocket-java#473]
Hi

I couldn't find any mentions of security in the rsocket protocol definition, but I did see some tests using secure websockets. 

Our current version of HAProxy does not support HTTP/2 so I was wondering if its possible to run rsocket-transport-netty with TCP and SSL and if there are any quirks by doing so?

UPDATE: think I misread websockets and HTTP/2 in the spec. Secure websocket for HTTP/1 is supported so I guess we could use that. 

Cheers,
-Kristoffer

**Comment by yschimke** [comment]
You are correct

Websocket(RS) over HTTP/1.1 SSL is already supported.
Websocket(RS) over HTTP/2 isn't a thing, but I don't think an upgrade mechanism is defined anyway.
TCP(RS) connection over SSL socket is probably possible with a small amount of custom setup code on client and server.

**Comment by krisskross** [comment]
Great, thanks!

**Comment by tmontgomery** [comment]
@yschimke Just FYI. https://tools.ietf.org/html/draft-ietf-httpbis-h2-websockets-00

Also, this came across the list yesterday. http://lists.w3.org/Archives/Public/ietf-http-wg/2018JanMar/0183.html

**Comment by yschimke** [comment]
Nice, assume it isn't supported in Netty yet :)

And for rsocket-android I *know* its not supported by OkHttp

**Comment by smaldini** [comment]
We're working the http2 support for reactor-netty 0.8 as well which we hope to get out at least with milestone in the next couple months or so.

**Comment by tmontgomery** [comment]
It may take some time to shake out. But with chrome implementing it, it will have momentum.

**Comment by krisskross** [comment]
Thanks for the info and salute for a great job (and collabo) on RSocket, especially on the protocol/core parts. 

I know this is a tough one but did you have discussions around inclusion in the JDK? Seems like a natural fit and building block for other reactive stream initiatives.

**Comment by yschimke** [comment]
Any interesting servers already for testing against?

**Comment by yschimke** [comment]
@krisskross to me having a separate release cycle seems easier.  Support for JDK 9 flowable types seems like the more interesting integration to me.  I haven't looked what that means for other libraries and frameworks.

**Comment by krisskross** [comment]
I haven't thought this one through, but the (reactive) knowledge spread within in the community would be valuable for sure. 

I just briefly browsed the code and it seems like the reactor dependency isn't that deep? Maybe reactive-streams-utils could help reducing the dependency on those parts? Who knows what will happen with our beloved ByteBuffer ;-)

**Comment by smaldini** [comment]
Implementing Publisher is hard, it took us to join forces with RxJava to do it right. Plus we have and will continue to add utils in reactor-core specifically for these use cases : 
- a bunch of proved operators
- only 2 high level types (Flux or Mono)
- context passing
- dropped data callback (per - flow ) to safely release in-flight ByteBuf
- advanced instrumentation to be used by adhoc libraries like Brave/Spring Cloud Sleuth (zipkin) and micrometer
- java 9 support via our bridge available in core too
- supported and enhanced by Spring Framework 5/Spring Boot 2

Reactive Streams is an interop contract, and it is a choice because async message passing is just a complex topic enough. Then its really opinionated the way you do it but you certainly don't want to do it yourself unless you implement a simple Subscriber. It's to easy to fail the TCK and too easy to have race conditions you only detect in production :( It took between rxjava and us a combined 4 years to get a set of operators right, with the right optimization as well because you don't want to pay async message passing for all use cases.

**Comment by rstoyanchev** [comment]
> Any interesting servers already for testing against?

Indeed, don't be misled by how thin `reactor-transport-netty` is. There is a huge amount of effort coming from the underlying `reactor-netty` dependency.

> reactive-streams-utils could help reducing the dependency on those parts

`reactive-streams-utils` is a nice idea (and it's just an idea currently) that may eventually help with the adoption of `Flow` within the JDK itself, or within Jakarta EE (Java EE). New JDK APIs currently in development have been reluctant to adopt and expose `Flow` which is too basic and not really meant as an application-level API. That's in part why `reactive-streams-utils` was suggested.

Outside the JDK, from an open source library perspective, things look very different. Unless what a library itself needs to do requires only 2-3 operators, and mind you that's rare, then your own library code needs a more complete reactive library as a core dependency for its own needs. At that point it makes no sense to hide those reactive types from your API. That doesn't preclude you from using other reactive libraries in your application. That's the point of Reactive Streams, to make that possible.

**Comment by krisskross** [comment]
> Implementing Publisher is hard, it took us to join forces with RxJava to do it right. 

No, no, sorry I apologize. I'm not trying to trivialize or criticize the efforts put into implementing RSocket or reactive-streams. I know that this stuff is hard and all you guys did a fantastic job. 

> reactive-streams-utils is a nice idea (and it's just an idea currently) that may eventually help with the adoption of Flow within the JDK itself, or within Jakarta EE (Java EE).

Exactly, is there enough experience within Oracle to create a reactive JDBC driver and HTTP client? I've read some statements which made me believe that they may need some help from the leaders of the reactive community? And this is also problematic... (Oracle) ... it would feel so comforting to see you guys in commit history of those modules :-)

> Not sure what you mean here but Netty's ByteBuf, due to its support for pooled direct buffers, is much better suited for a Reactive Streams chain, to minimize copying as data is passed from the application through to the network layer and the OS.

I think Netty ByteBuf is an excellent choice. I was referring to it as a dependency and accidentally added some unrelated ByteBuffer critique. Its unfortunate that we don't have language support or utils similar to what Netty Utils provide.

Bless!

**Comment by smaldini** [comment]
@krisskross the good thing is that for ByteBuf it should stay available as an independent lib in a near feature with possible improvements (becoming an interface, as CompositeByteBuf).

Sorry I misread your comment earlier, I thought you were referring to rebuilding from scratch an on purpose library. I have some reserves regarding the current RS-utils proposal and the need for such proposal at first in the JDK itself (David Karnok expressed them well [here](http://jsr166-concurrency.10961.n7.nabble.com/Reactive-Streams-Utility-API-td14647.html)). IMHO, we have an already amazing ecosystem between Akka Streams, RxJava, Vert.x, Ratpack and Spring/Reactor, all open-source. The fact that we had to incubate RS specification outside any JSR control should speak volumes about our perception at the time. Still today, the TCK and samples for the Flow JSR are still under reactive-streams github. JEE as a standard is much less impacting nowadays, which might be good or or bad depending on where you come from.  I think open-source is such today, people create pragmatic solutions and then federate more companies around in a viral way vs specification groups that require lockstep coordination, which might be better for protocols. Also the today developer is certainly more polyglot than before, JEE might just be too much in this saturated tech market.

Rambling apart, we have interesting experiments going on regarding reactive data access [here](https://github.com/nebhale/r2dbc) as the latest discussions about ADBA stalled a bit AFAIU. If you're interested don't hesitate to try it and feedback 👍

**Comment by krisskross** [comment]
>  I have some reserves regarding the current RS-utils proposal and the need for such proposal at first in the JDK itself (David Karnok expressed them well here).

I was following that conversation for a few rounds, but not until the end. Damn. Lets hope we can keep the vibes positive. But yes absolutely, I can't recall seeing anything like what the reactive community have become. Very refreshing both technically and "socially". And even Oracle are starting to soften up towards the community. I recall working at Ericsson around Java 6-7 and the efforts of pushing JSRs into the JCP -- mucho precarious. Many things feels/are better now.

> Regarding JEE, I think as a standard it is much less impacting nowadays, which might be good or or bad depending on where you come from. 

Yeah, and that's probably an understatement.

> Rambling apart, we have interesting experiments going on regarding reactive data access

I wasn't aware of R2DBC. Ill definitely try it out. Thanks!

Keep up the good work and don't let minor setbacks or people problems hold you back ... if there ever was such a thing :-)
