### ISSUE TITLE
Netty client websocket transport ignores connection disposal

### ISSUE THREAD

**Issue by mostroverkhov** [rsocket/rsocket-java#492]
In such case Client `RSocket.dispose()` does not trigger `RSocket.onClose()`, and `isDisposed()` stays false indefinitely. The problem is most likely in reactor-netty `NettyContext`, which does not call its  callbacks on termination.

**Comment by mostroverkhov** [comment]
@nebhale Tested against 0.7.8-SNAPSHOT and think It is not fixed yet - `onClose()` still not firing. I'll create issue on reactor-netty.

**Comment by violetagg** [comment]
yep we need additional change in Reactor Netty for `onClose` https://github.com/reactor/reactor-netty/issues/345

**Comment by violetagg** [comment]
the fix will be in Reactor Netty 0.7.8

**Comment by mostroverkhov** [comment]
0.7.8 released  already with fix for this issue

**Comment by sleoniy** [comment]
Still going on...

**Comment by OlegDokuka** [comment]
Working on fix
