### ISSUE TITLE
Separate run config for slow tests

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-java#511]
WebsocketSecureTransportTest.requestChannel2_000_000

takes 2 minutes to run for me locally.

**Comment by nebhale** [comment]
Let me take a crack at it.  Probably a tag and a configuration that disables that tag by default?  Need to do some JUnit 5 research.

**Comment by yschimke** [comment]
Thanks, I can see where the Junit 5 design is trying to be, but it's a very frameworky solution to implement these types of filters.  

Compared to TestNG

`@Test(groups = { "slow" })`

**Comment by nebhale** [comment]
JUnit would have supported `@Tag("slow")`, but the problem is that you can't disable that "group" by default in all possible execution environments (Gradle and IntelliJ).  I suspect the same is true for TestNG.
