### ISSUE TITLE
How to specify wss secure?

### ISSUE THREAD

**Issue by dawud-tan** [rsocket/rsocket-java#522]
How do I setup secure Wss?

**Comment by yschimke** [comment]
For the client look at https://github.com/rsocket/rsocket-java/blob/9f6fbcc02b1026c5826c2231bd161b557b2ee61f/rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/WebsocketClientTransport.java#L99

and

https://github.com/rsocket/rsocket-java/blob/bf14aa36cd10b59f22f2c323d93d24b266462be9/README.md

I think there is a bug in https://github.com/rsocket/rsocket-java/blob/9f6fbcc02b1026c5826c2231bd161b557b2ee61f/rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/WebsocketUriHandler.java#L62

So you will need to expand that and set the options yourself.

**Comment by rstoyanchev** [comment]
The `WebSocketUriHandler` alone is not sufficient. Take a look at the [Reactor Netty reference](https://projectreactor.io/docs/netty/release/reference/index.html#_ssltls) for transport level configuration. There is also [this test](https://github.com/rsocket/rsocket-java/blob/develop/rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebsocketSecureTransportTest.java).
