### ISSUE TITLE
WebSocket transports should expose configuration options

### ISSUE THREAD

**Issue by Ben-Mark** [rsocket/rsocket-java#525]
I couldn't figure out how to setup a sub-protocol to my websocket client
Can anyone help me with that?

many thanks!

~Ben

**Comment by yschimke** [comment]
I think you will need to clone WebsocketClientTransport, specifically you need to be able to change 

```
  @Override
  public Mono<DuplexConnection> connect() {
    return Mono.create(
        sink ->
            client
                .ws(path, hb -> transportHeaders.get().forEach(hb::set))
```

to pass in a third parameter.  a PR for this would be great ;)

**Comment by Ben-Mark** [comment]
Thanks for the clarification yschimke.
I'll soon send a PR

**Comment by rstoyanchev** [comment]
Both client and server Reactor Netty support a few options (sub-protocol, frame size, etc).

**Comment by rstoyanchev** [comment]
This should be possible after #844 which allows customizing the `WebsocketClientSpec` passed to `HttpClient`.
