### ISSUE TITLE
Cant send a proper JSON

### ISSUE THREAD

**Issue by Ben-Mark** [rsocket/rsocket-java#528]
Leaving the fact that the readme is far from whats published in the official project readme
Which by the way, doesn't compile (referred to the example)

The following snippet, isnt sending the json as is, its mutating it for some reason

RSocket rSocketClient = RSocketFactory.connect().keepAlive().transport(ws).start().block();

  Mono<Payload> payloadMono = rSocketClient.requestResponse(ByteBufPayload.create("valid JSON stringified");

What am I doing wrong?

**Comment by yschimke** [comment]
Thanks, I've now updated the https://github.com/rsocket/rsocket-java/blob/1.0.x/README.md example.

Could you submit an executable example?

I'm testing successfully with 

```
package io.rsocket.transport.netty;

import io.rsocket.*;
import io.rsocket.transport.netty.client.WebsocketClientTransport;
import io.rsocket.transport.netty.server.NettyContextCloseable;
import io.rsocket.transport.netty.server.WebsocketServerTransport;
import io.rsocket.util.DefaultPayload;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.net.URI;

public class DocExample {
    public static void main(String[] args) {
        WebsocketServerTransport wst = WebsocketServerTransport.create("localhost", 8988);
        SocketAcceptor acceptor = (setup, sendingSocket) -> Mono.just(new AbstractRSocket() {
            @Override
            public Flux<Payload> requestStream(Payload payload) {
                System.out.println("server saw " + payload.getDataUtf8());
                return Flux.just(DefaultPayload.create("{\"server\": 1}"));
            }
        });
        Mono<NettyContextCloseable> server = RSocketFactory.receive().acceptor(acceptor).transport(wst).start();

        WebsocketClientTransport wct = WebsocketClientTransport.create(URI.create("ws://localhost:8988/"));
        RSocket client = server.then(Mono.defer(() -> RSocketFactory.connect().keepAlive().transport(wct).start())).block();

        try {
            Flux<Payload> s = client.requestStream(DefaultPayload.create("{\"client\": 1}"));

            s.take(10).doOnNext(p -> System.out.println(p.getDataUtf8())).blockLast();
        } finally {
            client.dispose();
        }
    }
}
```

**Comment by Ben-Mark** [comment]
DefaultPayload.create
has no string input overload

my dependencies are as follows

compile('io.rsocket:rsocket-core:0.11.5')
compile('io.rsocket:rsocket-transport-netty:0.11.5')

plus note that

repositories {
    maven { url 'https://oss.jfrog.org/libs-release' }
}

dependencies {
    implementation 'io.rsocket:reactivesocket:0.9.20'
}

doesnt exist :/

**Comment by yschimke** [comment]
Thanks, it's now in maven central e.g.

https://mvnrepository.com/artifact/io.rsocket/rsocket-core/0.11.5

**Comment by Ben-Mark** [comment]
DefaultPayload.create still has no string input overload

**Comment by yschimke** [comment]
DefaultPayload.create

https://github.com/rsocket/rsocket-java/blob/4552053cfa622f4d0d7b133141e12d3b3eec5a75/rsocket-core/src/main/java/io/rsocket/util/DefaultPayload.java#L109-L111

**Comment by Ben-Mark** [comment]
I'm trying to send data to a remote server , written in C
It surely isn't implementing RSocket server on it
Is RSocket client strict to RSocket server only?

**Comment by yschimke** [comment]
Yes, it can only talk with an RSocket server.  If you have your own C Websocket server and implement a sequence of messages that matches the spec, it should work, but at that point you have implemented rsocket-c for us :)

**Comment by Ben-Mark** [comment]
O man :/
Sorry for the false alarm then
thanks alot for your help

Can you recommend any other non-blocking websocket client (not ReactorNettyWebsocket since it closes connection after every stream) ?

**Comment by yschimke** [comment]
You could drop down to raw Netty, or try Jetty

https://www.eclipse.org/jetty/documentation/9.4.x/jetty-websocket-client-api.html

**Comment by yschimke** [comment]
Have you reported your issue to the reactor project?

**Comment by Ben-Mark** [comment]
not yet , will do immediately

**Comment by Ben-Mark** [comment]
Thanks alot for your help, yschimke
