### ISSUE TITLE
Label or tag support for RSocket interface?

### ISSUE THREAD

**Issue by linux-china** [rsocket/rsocket-java#562]
RSocket is almost like session(context support), and is stored in a global list  for later usage on responder side sometimes.  For example: 

- filter some RSockets to send messages back
- priority support for some RSockets
- monitoring statistics 
- management metadata for RSocket 

Without label or tag support, and a global Map will be introduced to add extra information related with the RSocket, and it's very complicated. 

I will create a PR if somebody think this feature useful.

**Comment by yschimke** [comment]
This last came up in the context of supporting Reactor Core Context.  I think if your feature was to exist that these things should be related.  At the time it was deemed above rsocket-java library level, but potentially worth discussing.

**Comment by linux-china** [comment]
I think it's not Reactor Context.  Just make RSocket to be Map like to store some KV pairs, almost like ServletContext for Servlet.   I want to attach some atrributes to RSocket, then fetch attributes back according from sending socket. code like following: 
```
public class RSocketResponderHandler extends AbstractRSocket {

    public RSocketResponderHandler(ConnectionSetupPayload setupPayload, RSocket sendingSocket) {
        //todo parse setup payload
        sendingSocket.setAttribute("ip","192.168.1.2");
    }
    public Mono<Payload> requestResponse(Payload payload) {
        //how to get sending RSocket
        return Mono.just(payload);
    }
}
```

**Comment by yschimke** [comment]
My point was that once attached like this, it would be strange if it was not available via existing APIs

**Comment by linux-china** [comment]
@yschimke  I want to attach some information into peer RSocket and get them back in later operation.
For example,  during setup, and I attached ip, id and other information on sendingRSocket, then in requestResponse, and I want to retrieve these information.  the code like following:
```

Mono.just("Hello")
                .flatMap(s -> Mono.subscriberContext()
                        .map(ctx -> {
                            return s + " " + ctx.get("ip");
                        }));
```

Before sending the payload to peer RSocket, create a sendingRSocketContext and attach to Mono.
```
 monoFromRequestResponse.subscriberContext(sendingRSocketContext);
```
is this possible now?

**Comment by OlegDokuka** [comment]
@linux-china Hey buddy! I guess you want to implement something like that -> https://github.com/CollaborationInEncapsulation/reactive-pacman/blob/master/game-server/src/main/java/org/coinen/reactive/pacman/controller/rsocket/SetupController.java#L43

https://github.com/CollaborationInEncapsulation/reactive-pacman/blob/master/game-server/src/main/java/org/coinen/reactive/pacman/controller/rsocket/support/UuidAwareRSocket.java

**Comment by linux-china** [comment]
@OlegDokuka  yes. it's correct. could we make it default by RSocket-Java without a new SocketAcceptor?

**Comment by yschimke** [comment]
Tempted to close this if it hasn't moved in two years.  Would we do this the same way, or solve using Spring abstractions?
