### ISSUE TITLE
OpenTracing support

### ISSUE THREAD

**Issue by hzariv** [rsocket/rsocket-java#567]
Provide support for distributed tracing in RSocket clients and servers via OpenTracing. Distributed tracing follows a request on its journey from inception to completion from mobile/browser all the way to down steam services.

See: https://opentracing.io/

**Comment by hzariv** [comment]
@robertroeser thanks for clarification from documentations it was not obvious where OT was implemented. Will you support Jaeger (https://www.jaegertracing.io/) in addition to Zipkin?

**Comment by robertroeser** [comment]
@hzariv In theory it should work Jaeger as well. RSocket-rpc-java uses the open tracing API and we've tested it with both Jaeger and Zipkin. We can extend the tracing frame if it's missing information to make it work with Jaeger.

I opened an issue to create the RSocket metadata extension frames:
https://github.com/rsocket/rsocket-java/issues/568

**Comment by hzariv** [comment]
@robertroeser  thanks. I will close this issue for now since rsocket-rpc-java is providing OT on top of rsocket-java.

**Comment by ilterpehlivan** [comment]
Hi,
@robertroeser  do you have any example that you can share with me for tracing ? I am trying to make a simple Rsocket RPC client, server work with following dependencies:

compile "org.springframework.cloud:spring-cloud-starter-sleuth"
compile "io.opentracing.brave:brave-opentracing:0.33.10"
compile "io.opentracing:opentracing-api:0.31.0"

However I cannot make the server to receive any tracing ID!
Any help would be appreciated

Thanks
