### ISSUE TITLE
Move StreamId into DuplexConnections

### ISSUE THREAD

**Issue by nebhale** [rsocket/rsocket-java#580]
Currently the stream id leaks into the RSocket implementation above the `DuplexConnection`.  Given that the stream id and length are optional and required only in some transports, this concern should be moved down into the appropriate transports.

**Comment by robertroeser** [comment]
After looking at the code this change is going to need to be a little different. In the request (RSocketClient java) the stream id is also used to correlate the where frames go. I think what I'm going to do is update the FrameHeaderFlyweight to do two things. To make this work with other transports that provide there own stream ids. Firstly I'm going to provide a method let you replace the current stream id with the another one. The second thing I'm going to do is add a method to FrameHeaderFlyweight that will let you slice a section of the out going payload *without* the stream id. If a transport supports its own stream id we'll need to maintain an IntToInt map of ids in the implemenation to map them back and forth. I another other change at this point is probably going to be prohibitive.

**Comment by OlegDokuka** [comment]
close this as superseded by @878
