### ISSUE TITLE
Add [openjdk11] to Travis build matrix

### ISSUE THREAD

**Issue by robertroeser** [rsocket/rsocket-java#588]
Adding openjdk11 to the Travis build is causing a build error. Need to add openjdk11 back to travis build and fix the issue.

**Comment by mostroverkhov** [comment]
above change breaks build on `develop` due to javadoc related bug `javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.` https://travis-ci.org/rsocket/rsocket-java/builds/530167617
