### ISSUE TITLE
A way to "plug" RSocket into a Reactor HttpServer that's configured and managed externally

### ISSUE THREAD

**Issue by rstoyanchev** [rsocket/rsocket-java#601]
Currently `ServerRSocketFactory` is used to both initialize RSocket and start the underlying server which is done by passing a `ConnectionAcceptor` to the configured `ServerTransport`. 

For existing server setups like the Spring Boot "webflux" starter which already configures and starts a Reactor Netty `HttpServer`, it would be useful to be able obtain that `ConnectionAcceptor` and then effectively "plug" RSocket as a WebSocket route into its own `HttpServer` similar to what `WebsocketRouteTransport` does.

**Comment by OlegDokuka** [comment]
Implemented by #612 #600
