### ISSUE TITLE
Investigate resumability compatibility between java and js implementations

### ISSUE THREAD

**Issue by OlegDokuka** [rsocket/rsocket-java#602]
At the moment js client does not compatible with java receiver with resumable transport enabled

**Comment by dsibilio** [comment]
Was this issue ever verified? Does is still stand?

I'm working on an RSocket demo project (https://github.com/dsibilio/rsocket-demo) with a Java receiver and a Js client with WebSocket as transport.
Whenever I replace the app.js file to implement resumability (following the example here: https://github.com/rsocket/rsocket-js/blob/master/packages/rsocket-examples/src/ResumeExample.js), I can't connect to the socket anymore, not even once. It keeps looping, trying to connect.

Most likely I'm doing something wrong... :)
If you want to fiddle with the demo project all you have to do is:
1. Deploy the Java receiver with `mvn spring-boot:run`
2. Move into the `js-client` folder
3. Replace the index.js file with a resumable index.js implementation over WebSocket (the socket is @ ws://localhost:8080/tweetsocket and accepts a JSON Object like the following `{ "author": "linustorvalds }`
4. *(make sure you've got* ***browserify*** and ***nginx*** *installed with default root)* Run the following command 
```bash
browserify index.js > app.js && sudo cp app.js /usr/share/nginx/html/rsocket/ && sudo cp index.html /usr/share/nginx/html/rsocket/
```
5. Check results @ http://localhost/rsocket/index.html

**Comment by robertroeser** [comment]
@mostroverkhov can you take a look as you are familiar this

**Comment by OlegDokuka** [comment]
I guess the fix was merged into the muster but the muster was never realised since that time

**Comment by robertroeser** [comment]
@OlegDokuka do we need a new release of rs-js then? or do you mean rs-java?

**Comment by mostroverkhov** [comment]
This needs new release which would also include other feature for which there is pending request change in RSocket spec. RSocket-js build does not seem to publish snapshot binaries, so demo should reference RSocket-js head of `master`.

**Comment by robertroeser** [comment]
@mostroverkhov rsocket-java?

**Comment by mostroverkhov** [comment]
Release of rsocket-js
