### ISSUE TITLE
CloseableChannel#dispose ignored

### ISSUE THREAD

**Issue by pmackowski** [rsocket/rsocket-java#603]
I am trying to shutdown a receiver `RSocketFactory.receive()` through `CloseableChannel#dispose` method but it seems not to be working. Here is a test that I expect to pass:

```
@Test
public void closeReceiver() throws InterruptedException {

int randomPort = ThreadLocalRandom.current().nextInt(10_000, 20_000);

AtomicInteger results = new AtomicInteger();
CountDownLatch errorLatch = new CountDownLatch(1);

CloseableChannel closeableChannel = RSocketFactory.receive()
        .acceptor((setup, sendingSocket) -> {
            return Mono.just(new AbstractRSocket() {

                @Override
                public Flux<Payload> requestStream(Payload payload) {
                    return Flux.interval(Duration.ofMillis(100))
                            .onBackpressureDrop()
                            .map(i -> DefaultPayload.create("Response-" +i));
                }

            });
        })
        .transport(TcpServerTransport.create(randomPort))
        .start()
        .block();

RSocket sender = RSocketFactory.connect()
        .transport(TcpClientTransport.create(randomPort))
        .start()
        .block();

sender.requestStream(DefaultPayload.create("Request"))
        .subscribe(new BaseSubscriber<Payload>() {

            volatile Subscription subscription;

            @Override
            protected void hookOnSubscribe(Subscription subscription) {
                this.subscription = subscription;
                this.subscription.request(1);
                closeableChannel.onClose()
                        .doFinally(signalType-> {
                            // request more, should produce an error as receiver no longer produce
                            subscription.request(Integer.MAX_VALUE);
                        })
                        .subscribe();
            }

            @Override
            protected void hookOnNext(Payload value) {
                if (results.compareAndSet(0, 1)) {
                    // expecting it to stop the server
                    closeableChannel.dispose();
                } else {
                    results.getAndIncrement();
                }
            }

            @Override
            protected void hookOnError(Throwable throwable) {
                if (throwable instanceof ClosedChannelException) {
                    errorLatch.countDown();
                }
            }
        });

assertThat(errorLatch.await(1, TimeUnit.SECONDS))
        .withFailMessage("ClosedChannelException is expected").isTrue();
assertThat(results.get()).isEqualTo(1);

}
```

**Comment by pmackowski** [comment]
Possibly `dispose()` on this [rSocketServer](https://github.com/rsocket/rsocket-java/blob/develop/rsocket-core/src/main/java/io/rsocket/RSocketFactory.java#L521) should do the trick.

**Comment by pmackowski** [comment]
Implemented a quick fix as it is a must-have functionality for me (I am currently working on rsocket-raft implementation). Please take a look [here](https://github.com/rsocket/rsocket-java/compare/develop...pmackowski:603_closeable_channel_dispose). Maybe you will find it useful in some way.

**Comment by robertroeser** [comment]
both sides have an rsocket-server so we don't want to return that to the user. Closing the channel should shut it down. If its not we should look into that.

**Comment by pmackowski** [comment]
Thank you for quick reply. 
My intention is not to expose anything to the user. Let me describe the problem in the pseudocode.

**On server 1**
```
CloseableChannel closeableChannel = RSocketFactory.receive()
       .acceptor(onRequestStream -> return payload every one minute)
       .transport(...)
       .start()
       .block()

// After 2 minutes
closeableChannel.dispose()

```
**On server 2**
```
RSocket sender = RSocketFactory.connect(Server 1)
                .transport(...)
                .start()
                .block()

sender.requestStream(DefaultPayload.create("Request"))
                // expected 2 payloads, no more
                .subscribe(payload -> {})
```

I expect `Server 1` to stop sending payloads to `Server 2` after two minutes.

**Comment by OlegDokuka** [comment]
Indeed, currently, a server is getting disposed once all streams are down but not at the dispose function call. This is a bug I guess. Will have a look shortly

**Comment by ilterpehlivan** [comment]
Hi,
 
I am also having the same issue, in my test case I am trying to stop Rsocket server and reinitialize it to be able to see LoadbalancerMono client behaviour. However Rsocket server is never disposing

closeableChannel.dispose()
rsocket.dispose()

But service is never going down even though I wait more than 2 seconds

Any estimate when this might be fixed ?
Thanks

**Comment by robertroeser** [comment]
@OlegDokuka - can you help out here?

**Comment by fvigotti** [comment]
using ` 0.12.2-RC4`  seems that `dispose()` on a connection created with 
```kotlin
val address = InetSocketAddress.createUnresolved(host, port)

        //val addres = TcpServerTransport.create("localhost", port)
        val tcpAddr = TcpServerTransport.create(address)
        this.server = RSocketFactory
            .receive()
            .acceptor { _, _ -> Mono.just<RSocket>(dispatcher) }
            .transport<CloseableChannel>(tcpAddr)
            .start()
            .onTerminateDetach()
            .block()!!
```
( even when used at start, without opened connections )
is completely broken, isDisposed return true, but the server accept & reply to incoming connection someone know if there is a workaround to use while the bug is fixed ? (I'm not enough expert in the library to implement myself ) 
thank you

**Comment by mostroverkhov** [comment]
This is intended way of how reactor-netty handles server dispose - existing connections are not getting closed. Can be worked around with something like https://github.com/rsocket/rsocket-java/tree/bugfix/server-dispose

**Comment by fvigotti** [comment]
Thanks  @mostroverkhov  but at the moment I'm not inclined to use a forked branch of dev in a production software, I was looking for something like a kill-switch for a netty/rsocket library to introduce somewhere,  I need to dispose connections mainly for my integration tests inside the app.. 
also as I said, no just **existing** connetions continue as nothing happened ( and the socket doesn't close & release the port ) but even **NEW** connections can start after `.dispose()` has been called , to me sound very weird that there isn't a way in netty to force/close the socket..  , 
thank you,
Francesco

**Comment by OlegDokuka** [comment]
Starting from the 0.9.6 Reactor-Netty release (now used in RSocket RC7-SNAPSHOT) supports a built-in mechanism for graceful shutdown. For more information see https://github.com/reactor/reactor-netty/pull/1034
