### ISSUE TITLE
decoupling of Reactor implementation

### ISSUE THREAD

**Issue by michaelom** [rsocket/rsocket-java#625]
The `rocket-core` artifact depends on Spring Reactor:

```
api 'io.projectreactor:reactor-core'
```

This is a pesky dependency for projects that use rxjava2, vertx or akka-streams.

I was wondering 
- if the core module could remain vendor neural and depend only on `org.reactivestreams:reactive-streams`
- the Reactor dependency could be moved to a dedicated 'rsocket-reactor' module.

**Comment by michaelom** [comment]
FYI: RxJava has a documentation section describing different approaches how to deal with exposes APIs:
https://github.com/ReactiveX/RxJava/wiki/Reactive-Streams#public-apis-of-libraries

**Comment by smaldini** [comment]
Our thinking has slightly evolved from 4 years ago when this was posted by Ben there and especially on rsocket side it brings us quite a few benefits to depend on reactor, which you can easily interop with any of the libraries mentioned above. The same people behind the guidelines you mentioned, rsocket, rxjava and reactor make this project.

We designed both rxjava2 and reactor with the same core so both translate well with what we do here, we also can differentiate single/many publisher types. Reactive Streams is an interop for that reason. Now amongst other benefits we can use reactor context in important jvm libraries like spring to propagate informations, we can use fusion, we can use schedulers and above all we can use operators that are not defined by the specification. The protocol is open enough to have alternative drivers but even things like https://github.com/rsocket/rsocket-transport-akka just work nicely enough with reactor. Why is that such a big deal especially if you are related to another lib like rx with natural interoperability ?

**Comment by smaldini** [comment]
Unless we have a clear benefit, we don't have plans in the immediate future to operate that change so I'm closing for the time being.
