### ISSUE TITLE
Resume working for connection but not a stream

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-java#637]
Reproducible with the rsocket-cli project

```
./rsocket-cli --resume --server -i @/usr/share/dict/words ws://localhost:5001
socat -d TCP-LISTEN:5000,fork,reuseaddr TCP:localhost:5001
./rsocket-cli -i Obama --debug --stream --resume ws://localhost:5000
```

kill and restart socat

```
agamogenesis
agamogenetic
agamogenetically
agamogony
16:19:15.491	client Inner connection disconnected: ClosedChannelException
16:19:15.492	Client session connection error. Starting new connection
16:19:15.539	client Transport send completed: onError, io.rsocket.keepalive.KeepAliveConnection@2e35da9e
16:19:18.552	client Resumable duplex connection reconnected with connection: io.rsocket.internal.ClientServerConnection@52af0cd2
16:19:18.553	Switching transport: client
16:19:18.554	Upstream subscriber requestN: 256
16:19:18.554	Client ResumableConnection reconnected. Sending RESUME frame with state: [impliedPos: 70003, pos: 0]
16:19:18.555	sending ->
Frame => Stream ID: 0 Type: RESUME Flags: 0b0 Length: 44
Data:

16:19:18.576	client Inner connection disconnected: ClosedChannelException
16:19:18.577	Client session connection error. Starting new connection
16:19:18.577	client Transport send completed: onError, io.rsocket.internal.ClientServerConnection@52af0cd2
16:19:21.589	client Resumable duplex connection reconnected with connection: io.rsocket.internal.ClientServerConnection@307a6a6f
16:19:21.590	Switching transport: client
16:19:21.590	Upstream subscriber requestN: 256
16:19:21.590	Client ResumableConnection reconnected. Sending RESUME frame with state: [impliedPos: 70003, pos: 0]
16:19:21.590	sending ->
Frame => Stream ID: 0 Type: RESUME Flags: 0b0 Length: 44
Data:

16:19:41.601	receiving ->
Frame => Stream ID: 0 Type: KEEPALIVE Flags: 0b0 Length: 14
Data:
```

**Comment by yschimke** [comment]
I'm on io.rsocket:*=0.12.2-RC2

https://github.com/rsocket/rsocket-cli/blob/master/versions.props#L13

**Comment by yschimke** [comment]
I suspected it could be backpressure related, I was streaming the dictionary line by line as fast as possible. So without a connection, it's possible I was overwhelming things on the server side while there was no IO to slow things down.

But the interval timer isn't working either.

```
it diff
diff --git a/src/main/kotlin/io/rsocket/cli/Main.kt b/src/main/kotlin/io/rsocket/cli/Main.kt
index 8da5209..8d32667 100644
--- a/src/main/kotlin/io/rsocket/cli/Main.kt
+++ b/src/main/kotlin/io/rsocket/cli/Main.kt
@@ -308,7 +308,7 @@ class Main {
   }

   private fun inputPublisherX(): Flux<Payload> {
-    return inputPublisher.inputPublisher(input ?: listOf("-"), buildMetadata())
+    return Flux.interval(Duration.ofMillis(500)).onBackpressureDrop().map { DefaultPayload.create("" + it) }
   }

   private fun singleInputPayload(): Payload {
```

**Comment by yschimke** [comment]
Also I can see that the server is maintaining the stream, since in the twitter example it isn't doing the unsubscribe which happens on cleanup.

**Comment by yschimke** [comment]
Since it is working with rsocket-java test, but failing with rsocket-cli, which is less well maintained; I'm happy to treat this as rsocket-cli bug until proven otherwise.

**Comment by mostroverkhov** [comment]
This needs investigation with non CLI java only setup - same client, server handler etc. I will be able to check this monday evening

**Comment by mostroverkhov** [comment]
@yschimke I quickly updated resume example to something similar what CLI does above - can you give It a try?

**Comment by yschimke** [comment]
Will do tonight

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yschimke** [comment]
Not sure what you observed, but it reconnected for me, but ultimately I ended up with looping content which surprised me.  Couldn't see that in the branch changes either.

**Comment by mostroverkhov** [comment]
It loops because there is `repeat` in file source - otherwise test stops very quickly to test how disconnects influence resumption. If this reconnects successfully for you (as It does for me) , and does not hang, then I suggest to look for issues inside rsocket-cli

**Comment by yschimke** [comment]
Yep, thanks, will do.

It's absolutely flying through once it warms up.  Thanks for humoring me!

**Comment by yschimke** [comment]
cli -> your server = resume works.

**Comment by yschimke** [comment]
Changed the cli to use a slower interval timer (1/sec) source and it's all good.  I think the stream from a file source just overwhelms the server when there is no connected client.  Not convinced things are in a good state after that point.  But it's working end to end in the happy resume path.

Thanks for the help.

**Comment by mostroverkhov** [comment]
Maybe try add `.limitRate(n)` on receiving side? Then on disconnect there will be at most N items in resume cache.
