### ISSUE TITLE
RSocketInterceptor does not have access to metadataMimeType and dataMimeType

### ISSUE THREAD

**Issue by rwinch** [rsocket/rsocket-java#661]
# Summary

Payload provides the ability to access the metadata and the data, but users cannot read these values without knowing the corresponding mime types. Payload should contain the mime types so users can read the metadata and data values.

# Background

I'm working on RSocket & Spring Security support. I’d like to create an RSocketInterceptor to wrap the RSocket with security concerns (authentication / authorization). For this to work security will need to be able to read the Payload. For example, security will need to read the metadata to get credentials for authentication. It will also need to get the metadata to get the route information to perform authorization based logic.

How should I read the Payload metadata from inside an RSocket implementation so security can perform authentication and authorization. The problem I'm having is that while the RSocket API exposes the Payload which contains the metadata, it does not appear to expose the metadataMimeType (or the dataMimeType).

Spring creates a SocketAcceptor (RSocketMessageHandler) which obtains the Mime Types from the ConnectionSetupPayload. It then ensures that the RSocket it creates has a reference to the mime types. I don't think it makes sense for someone implementing RSocketInterceptor to have to also implement and wrap downstream SocketAcceptor to get the mimetypes for metadata and data.

**Comment by robertroeser** [comment]
We didn't do this before because there is only one time type for the data and metadata at connection time - it doesn't change. The payload should be always the be same mime-type to be handled properly. In the case where might need something else we added the composite metadata extension.

**Comment by rwinch** [comment]
Thanks for the response  @robertroeser. I'm not sure I understand.

> We didn't do this before because there is only one time type for the data and metadata at connection time - it doesn't change. 

I'm confused because "this before" implies the reasoning for the past. However, "there is only one time type" implies there this is still true.

Perhaps I'm reading into it too much but I'm just curious if you are saying that it wasn't done before, but now it should be changed or that it still doesn't need to change?

**Comment by robertroeser** [comment]
Cleaned up the sentence - We didn't do this before because there is only one type of mimetype for data and metadata at connection time - it doesn't change.

**Comment by rwinch** [comment]
@robertroeser Thanks for the response. It's probably better that I state the problem rather than try to propose a solution.

I'm creating an `RSocketInterceptor` to handle security concerns. It needs to work as an interdependent component. It will need to parse the metadata to obtain the user credentials for authentication. It will also need to parse the metadata to obtain the route so it can perform authorization. It is possible it will need to parse the data as well. In order to parse either the metadata or the data, the `RSocketInterceptor` needs to know the mime type for both the metadata and the data.

Is there for an `RSocketInterceptor` that works as an independent component to access the mime type for metadata and data?

**Comment by rstoyanchev** [comment]
> It's probably better that I state the problem rather than try to propose a solution.

@rwinch can you also update the title to reflect the problem?

**Comment by rstoyanchev** [comment]
I've sent https://github.com/rsocket/rsocket-java/pull/676 with a proposal to address this. 

In addition, based on the way `RSocketInterceptor` is applied, we have found it is not possible to pass security context down the processing chain through the Reactor Context, which is a major issue for security. I believe the proposal will resolve that problem too because decorating `SocketAcceptor` allows hooking into the `Mono<RSocket>` return value but I have not verified this.

**Comment by rwinch** [comment]
Thanks for the PR @rstoyanchev! gh-676 now makes it easy to access the mimetypes through the use of the plugin mechanisms.
