### ISSUE TITLE
Tuple3ByteBuf issue

### ISSUE THREAD

**Issue by aaronchenwei** [rsocket/rsocket-java#663]
We are currently have a rsocket use case that we are requesting with both metadata and data. Hence our metdata and data bytebuf is processed by `DataAndMetadataFlyweight` through `rsocket-core`.

We just noticed that rsocket server side received message with data overriding metadata section. We traced the issue to class `Tuple3ByteBuf`

https://github.com/rsocket/rsocket-java/blob/fa5f179986b56cf56c43327ad789101b4fa7102a/rsocket-core/src/main/java/io/rsocket/buffer/Tuple3ByteBuf.java#L145-L147

In our case, the length of oneBuffer, twoBuffer and threeBuffer is 1. Furthermore our twoBuffer (metadata) and threeBuffer(data) are with type `UnpooledSlicedByteBuf`

Line 147 copies to the same location as line 146. 

In our case, the fix should be in line 147 with 
```java
 System.arraycopy(threeBuffer, 0, results,  oneBuffer.length + twoBuffer.length, threeBuffer.length);
```

I haven't gone through all the use cases for class `Tuple3ByteBuf `. Could you please verify and advise how to address our issue?

**Comment by robertroeser** [comment]
Your metadata and data are length 1?

**Comment by aaronchenwei** [comment]
@robertroeser 

Thanks for asking the question. 

Let me give you more information about our issue.

Our test payload is created for example like below. The payload is sent through client's setupPayload method call.
```java
ByteBufPayload.create("foobar", "bar")
```
- data is "foobar" with length 6
- metadata is "bar" with length 3

`ByteBufPayload.create` would create `PooledUnSafeDirectByteBuf` for data and metadata separately.

`SetupFrameFlyweight` would call 

https://github.com/rsocket/rsocket-java/blob/42eaddea73e92a23f20846275fe4687d87cd3090/rsocket-core/src/main/java/io/rsocket/RSocketFactory.java#L349-L360

`sliceMetadata` and `sliceData` would return metadata and data as `UnpooledSlicedByteBuf`

Then above payload is sent to DataAndMetadataFlyweight and return an instance of `Tuple3ByteBuf`

https://github.com/rsocket/rsocket-java/blob/fa5f179986b56cf56c43327ad789101b4fa7102a/rsocket-core/src/main/java/io/rsocket/buffer/Tuple3ByteBuf.java#L130-L148

L139 `two.nioBuffers(twoReadIndex, l)` returns ByteBuffer[] with length 1 (similar to L142 for three). It is an array with its first element pointing to medata (or data) ByteBuf.

The rsocket server side is receiving
```
08:59:33.990 [reactor-tcp-nio-6] DEBUG io.rsocket.FrameLogger - receiving -> 
Frame => Stream ID: 0 Type: SETUP Flags: 0b100000000 Length: 68
Metadata:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 66 6f 6f                                        |foo             |
+--------+-------------------------------------------------+----------------+
Data:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 62 61 72 62 61 72                               |barbar          |
+--------+-------------------------------------------------+----------------+
```
data with value "foobar" override metadata "bar" and the result become medata "foo" and data "barbar"

**Comment by robertroeser** [comment]
Yes this is a problem - with the Tuple3ByteBuf - everything should more like ` System.arraycopy(threeBuffer, 0, results,  oneBuffer.length + twoBuffer.length, threeBuffer.length);`
Otherwise it won't start at the right offset.

**Comment by aaronchenwei** [comment]
Verified with version `1.0.0-RC2`. The issue mentioned here has been resolved. 

Thanks a lot for your quick fix. @robertroeser
