### ISSUE TITLE
Question: workarounds for missing cold resumption

### ISSUE THREAD

**Issue by dpfg** [rsocket/rsocket-java#664]
Hello everyone,

I've being evaluating RSocket for my next project where many clients will be connected to a couple of servers. RSocket seems quite nice: simple, but functional. 
In my case servers can go down periodically so clients should automatically reconnect when server is up. Basically, I don't care about lost messages. What is critical is to resume transmission. If I understood correctly out of the box rsocket-java doesn't support this type of resumption. 

The question is there any workaround that can be implemented on application level to gracefully handle server restarts? I'm not quite proficient in reactor and would appreciate any directions.

**Comment by mostroverkhov** [comment]
Hi, cold resumption is not available yet, and should be implemented in library - there is no way to workaround this. Cold resumption is trickier than warm one, given streams themselves can be cold (e.g. transferring large file as messages stream) or warm (e.g. notifications). Here, in addition to resuming with already sent items of stream, we need to restore `Responder` with proper state. same applies to requesters streams: they have to be correlated with ones before restart, and e.g. send cancellation signal if not subscribed after resumption.

**Comment by robertroeser** [comment]
@dpfg hi - are you asking if there is a way to automatically reconnect when your application restarts?

**Comment by dpfg** [comment]
@robertroeser this is exactly what I was looking for. Thank you!
