### ISSUE TITLE
Stream ID overflow instead of re-use

### ISSUE THREAD

**Issue by xiazuojie** [rsocket/rsocket-java#666]
According to [spec](http://rsocket.io/docs/Protocol#stream-identifiers),
when "max Stream ID has been used (2^31-1), the Requester MAY re-use Stream IDs" by "wrapping and restarting at ID 1 for client, and ID 2 for server".

Current [Java implementation](https://github.com/rsocket/rsocket-java/blob/21c39bdaa60c6a916e3288048b268f2b756dd5e7/rsocket-core/src/main/java/io/rsocket/StreamIdSupplier.java#L40) does not do re-use. In fact, after Integer.MAX_VALUE, stream id overflows to Integer.MIN_VALUE+1

**Comment by xiazuojie** [comment]
related to https://github.com/rsocket/rsocket-js/issues/40

**Comment by robertroeser** [comment]
This should fix the issue - see #667

**Comment by robertroeser** [comment]
fixed with release 1.0 RC2
