### ISSUE TITLE
Upgrade to Reactor Dysprosium

### ISSUE THREAD

**Issue by rstoyanchev** [rsocket/rsocket-java#670]
When trying to upgrade `spring-messaging` to `rsocket-core` version `1.0.0-RC1` from `0.12.2-RC4` I started getting consistent JVM crashes in all integration tests. This is with JDK `1.8.0_222-b10`. 

I noticed if I build `rsocket-core` with Dysprosium and use that instead, then `spring-messaging` tests are back to green. I don't know why but given Reactor Dysprosium should be ready in time for RSocket Java 1.0.0, is there any reason for RSocket Java not to aim to depend on that? If not, could the `develop` branch be upgraded to Dysprosium?

**Comment by robertroeser** [comment]
Sounds good - can you submit a pull request to upgrade RSocket to Dysprosium?
