### ISSUE TITLE
Maven: Could not resolve dependencies for io.rsocket:rsocket-core:jar:1.0.0-RC3

### ISSUE THREAD

**Issue by maxim-bandurko-lsvt** [rsocket/rsocket-java#693]
Hello.

There is an issue with dependencies at Maven:

SEVERE: Failed to execute goal on project: Could not resolve dependencies for project. Failed to collect dependencies at io.rsocket:rsocket-core:jar:1.0.0-RC3: Failed to read artifact descriptor for io.rsocket:rsocket-core:jar:1.0.0-RC3: Failure to find io.projectreactor:reactor-bom:pom:Dysprosium-M3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced.

Can it be it fixed?

Thanks!

**Comment by robertroeser** [comment]
Hi @maxim-bandurko-lsvt 

Glad to help - where are you getting this error? Is it  an error in a local build?

Thanks,
Robert

**Comment by maxim-bandurko-lsvt** [comment]
Hello @robertroeser 

Error comes when trying to copy all dependencies.  Like:
mvn dependency:copy-dependencies

It is because POM for reactor-bom-Dysprosium-M3 release not exists any more and is still inside dependency.

Downloading from central: https://repo.maven.apache.org/maven2/io/projectreactor/reactor-bom/Dysprosium-M3/reactor-bom-Dysprosium-M3.pom

Thanks!

**Comment by robertroeser** [comment]
@smaldini maybe you can help? This is a milestone release I believe so your might need to add repository for the build to work.

**Comment by spencergibb** [comment]
Yes, https://repo.spring.io/milestone

**Comment by linux-china** [comment]
@maxim-bandurko-lsvt    please add following on your pom.xml

```
  <repositories>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/libs-milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
```

**Comment by maxim-bandurko-lsvt** [comment]
@linux-china Worked well, thank you!
