### ISSUE TITLE
How to detect termination from server on javascript browser client?

### ISSUE THREAD

**Issue by mmihael** [rsocket/rsocket-java#705]
I'm using java rsocket lib for server and javascript rsocket browser lib for client.

Now, what I want to understand, is how to terminate the connection on the server during the connection setup request.

I have an implementation of SocketAcceptor interface that will check connection setup payload for some token to validate the connection.

If that token is invalid I want to terminate the connection.
At the moment I'm doing this:
```java
    @Override
    public Mono<RSocket> accept(ConnectionSetupPayload connectionSetupPayload, RSocket rSocket) {
        
        ...

        log.warn("Could not authorize socket access");
        rSocket.dispose();
        return null;
    }
```

An issue that I find is that even after calling `dispose` websocket connection is still open on fronted.
Looking from dev tools there is no indication that server terminated that connection.

**Comment by OlegDokuka** [comment]
@mmihael Hi Mihael! Try simply return `Mono.error(new SomeExceptionHere())` which basically terminate the connection sending an error frame to a client

**Comment by OlegDokuka** [comment]
I'm closing this ticket but feel free to ping me in case of anything
