### ISSUE TITLE
Dynamic MTU

### ISSUE THREAD

**Issue by Zeymo** [rsocket/rsocket-java#711]
In different net-situation usually want different MTU. In wifi or 4G we want set MTU 10 * 1024 and in weakness 3G or 2G set MTU to 1024 . It's relate to MTU level or Application-chunk-level ？If MTU ,  how to adjust MTU in Runtime

**Comment by OlegDokuka** [comment]
He @Zeymo! Thanks for asking the question!

I do not think it possible right now, and I think it does not make any sense. Let me explain why:

Every time your network type has changed (e.g., 2g->3g->4g), under the hood, you are losing your underlying connection (correct me if I'm wrong). It means then you would need to reestablish your, for instance, TCP connection (which could be done automagically), but in any case, the previous one will be unavailable anymore. 
 Then, you would need to restart your stream using, e.g. reusability feature of RSocket. By doing that, you can always check the network type and set up a new MTU size.

**Comment by OlegDokuka** [comment]
Also, in the context of RSocket MTU means the maximum size of `ByteBuf` sent over the wire ( it means that your payload is going to be split into a several `ByteBuf`s and flushed out to the network )

**Comment by OlegDokuka** [comment]
I'm closing this issue for now. Feel free to reopen if you got more questions!

Regards,
Oleh

**Comment by Zeymo** [comment]
thx for ur time
