### ISSUE TITLE
Document use of LoadBalancedRSocketMono parameters

### ISSUE THREAD

**Issue by pckeyan** [rsocket/rsocket-java#725]
This question related to https://github.com/rsocket/rsocket-java/issues/717 and @OlegDokuka recommendation.

I am using the LoadBalancedRSocketMono to load balance my servers. I use to get the `Connection Reset by Peer` exception. Based on recommendation, I am planning to play with the below parameters, but I am not able to find document for values, its significance and low/upper limits etc. I do read the javadoc but above information is missing. Can you please help me understand on how I can play with the below parameters to get maximum performance?

```
public static final double DEFAULT_EXP_FACTOR = 5.0;

    public static final double DEFAULT_LOWER_QUANTILE = 0.2;

    public static final double DEFAULT_HIGHER_QUANTILE = 0.8;

    public static final double DEFAULT_MIN_PENDING = 1.0;

    public static final double DEFAULT_MAX_PENDING = 2.0;

    public static final int DEFAULT_MIN_APERTURE = 500;

    public static final int DEFAULT_MAX_APERTURE = 5000;

    public static final long DEFAULT_MAX_REFRESH_PERIOD_MS =
            TimeUnit.MILLISECONDS.convert(5, TimeUnit.MINUTES);
```

**Comment by OlegDokuka** [comment]
closes in favor of #915
