### ISSUE TITLE
Ability to intercept requests and access channel information such as remote address

### ISSUE THREAD

**Issue by NizGh** [rsocket/rsocket-java#735]
As in webflux we can retrieve the remote address from serverWebExchange.getRequest().getRemoteAddress(), what are alternatives to extract connection/channel information in rsocket?

**Comment by linux-china** [comment]
Now  you can get the remote address by tricky way. 

* TcpDuplexConnection has a  connection attribute with reactor.netty.Connection type, and you can use   connection.channel().remoteAddress() to get remote address
* Write a DuplexConnectionInterceptor plugin on server to intercept DuplexConnection,  if  duplexConnection is instance of WebsocketDuplexConnection or TcpDuplexConnection, and you can get Netty connection attribute.
