### ISSUE TITLE
RSocket resume session/stream after connection is lost

### ISSUE THREAD

**Issue by bpetrovbg** [rsocket/rsocket-java#737]
I am using RSocket channel and trying to implement resume functionality, in case the connection to the server is lost. After trying different combinations of resume(), resumeSessionDuration(), resumeStreamTimeout() and resumeCleanupOnKeepAlive() /documentation: https://javadoc.io/static/io.rsocket/rsocket-core/1.0.0-RC3/io/rsocket/RSocketFactory.ServerRSocketFactory.html#resume--/ on the server and the mobile device, still nothing happens. On the mobile device I send data to the server each 10 seconds and when the connection is lost, the socket is disposed at the 3rd retry. Does anyone know what all these methods exactly do server- and client-side? There is almost no documentation at all...

This is the code on the server:

```
RSocketFactory.receive()
                    .resume()
                    .acceptor((setupPayload, reactiveSocket) -> Mono.just(responseHandler))
                    .transport(TcpServerTransport.create(buildSecuredTcpServer(address, port, 
                    sslContext)))
                    .start()
                    .block();
```

The is the code on the mobile device:
```
socket = RSocketFactory.connect()
        .errorConsumer(throwable -> {
            if (throwable instanceof RejectedResumeException){
                Log.d("tagg", "error: " + throwable.getMessage());
            }
        })
        .resume()
        .resumeStreamTimeout(Duration.ofSeconds(120))
        .resumeSessionDuration(Duration.ofSeconds(600))
        .keepAlive(Duration.ofSeconds(120), Duration.ofSeconds(120), 120)
        .resumeStrategy(() -> new PeriodicResumeStrategy(Duration.ofSeconds(1)))
        .metadataMimeType(BuildConfig.RSOCKET_METADATA_MIME_TYPE)
        .dataMimeType(BuildConfig.RSOCKET_DATA_MIME_TYPE)
        .transport(TcpClientTransport.create(tcpClient))
        .start()
        .block();
Objects.requireNonNull(socket)
        .requestChannel(Flux.from(this::onSubscribe))
        .doOnNext(this::receiveData)
        .retryBackoff(Integer.MAX_VALUE, Duration.ofSeconds(1))
        .subscribe();
```

**Comment by mostroverkhov** [comment]
@bpetrovbg there is runnable [example](https://github.com/rsocket/rsocket-java/blob/develop/rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/resume/ResumeFileTransfer.java) that can be use das starting point. Generally you should enable resume and configure session duration (`RSocketFactory.resume(), resumeSessionDuration()`) on both sides, and set resume strategy on client.

**Comment by OlegDokuka** [comment]
@bpetrovbg fill free to reopen this if not clarified or there is anything else
