### ISSUE TITLE
Whitelist client IP address

### ISSUE THREAD

**Issue by kacper-emersoft** [rsocket/rsocket-java#743]
As per title, is there any way to whitelist client IP address?

**Comment by spencergibb** [comment]
Whitelist typically means always allow, is there something blocking your ip address. Can you explain what problem you are experiencing and why you believe a whitelist is needed?

**Comment by kacper-emersoft** [comment]
I have created a rsocket server and few clients. I want to restrict access to my rsocket server that only clients with given IP address should be able to connect to my server. . Is it possible to achive that on rsocket server level?

**Comment by OlegDokuka** [comment]
I think rsocket has no relation to that. Usually, such a configuration happens on the infrastructure level. 

Are there any reasons to put it on the rsocket level?

**Comment by kacper-emersoft** [comment]
I agree that infrastructure level is a good place to handle this. I was just wondering if such feature can be obtained on setup phase. If no. I'm fine with it. Thanks!

**Comment by OlegDokuka** [comment]
Theoretically, your client can include its IP address, however, in many cases, it is impossible to do. 
You can imagine:

* A Docker container calling another docker container. 
* A client calling another over a local, in-memory transport (so, technically there is no any opened port at all)
* A client is connected to a server over a transport that does not support IP-transmitting 

So, in general, there are many limitations and if such logic is a requirement i is better to implement some handshake on your own.

Closing this issue.

Regards,
Oleh

**Comment by linux-china** [comment]
@kacper-emersoft   you can build one interceptor  to verify whitelist clent IP.   https://github.com/rsocket/rsocket-java/issues/735

**Comment by kacper-emersoft** [comment]
@linux-china Thanks for great tip! Two questions regarding implementation:
1. As far as I can see, connection field is private. Is there any other way than access it via reflection? 
2. How to react in my DuplexConnectionInterceptor in case of IP missmatch? Throw an exception?

**Comment by linux-china** [comment]
>> As far as I can see, connection field is private. Is there any other way than access it via reflection?
you can use reflection reflection to access connection field

 >> How to react in my DuplexConnectionInterceptor in case of IP missmatch? Throw an exception?
Yes. you can send an error with REJECTED_SETUP to requester.  

```
REJECTED_SETUP | 0x00000003 | The server rejected the setup, it can specify the reason in the payload. Stream ID MUST be 0.
```

The example code as following(not tested):

```
.addConnectionPlugin(new DuplexConnectionInterceptor() {
                    @Override
                    public DuplexConnection apply(Type type, DuplexConnection duplexConnection) {
                        //todo get connection from DuplexConnection and check whitelist
                        ByteBuf byteBuf = ErrorFrameFlyweight.encode(ByteBufAllocator.DEFAULT, 0, new RejectedException("not in whitelist"));
                        duplexConnection.sendOne(byteBuf);
                        duplexConnection.dispose();
                        return duplexConnection;
                    }
                })
```

**Comment by kacper-emersoft** [comment]
@linux-china It is almost working.
Connection is not rejected immediately. Client does not get any error while connecting. He receives 500 error only after calling requestResponse (or any other exchange method). I can't find "not in whitelist" message aswell. This is what client is getting:
```java.nio.channels.ClosedChannelException: null
	at io.rsocket.RSocketRequester.terminate(RSocketRequester.java:476) ~[rsocket-core-1.0.0-RC5.jar:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
```
Anyway to drop connection immediately with meaningfull rejection reason printed on client side?

**Comment by linux-china** [comment]
you can use onErrorResume operator to make a new request.  But you should remove this closed rsocket from your list, and it's a features of load balance.  The following code just for refer. 
```
 return rsocket.requestResponse(payload)
                .onErrorResume(ClosedChannelException.class, error -> {
                   //remove rsocket from list 
                   onRSocketClosed(rsocket);
                    return requestResponse(payload);
                });
```

**Comment by kacper-emersoft** [comment]
What I was asking about is how to get an error on client side immediately after connecting? Right now I need to make a request to know that connection was closed. I would love to get reject upon initial connection try

**Comment by linux-china** [comment]
```
rsocket.onClose().doOnTerminate(() -> {
        //logic for closed event
        });
```

**Comment by kacper-emersoft** [comment]
@linux-china After your advices I started digging for other interceptors. I found a `SocketAcceptorInterceptor` where you can pass a custom `SocketAcceptor`. 
This is what I came up with. Ugly as hell because most of the fields are private so I was forced to use reflections. But it is working as expected. Client is immediately rejected in setup phase. 
```
@RequiredArgsConstructor
public class IPAddressAcceptor implements SocketAcceptor {

    private final SocketAcceptor delegate;
    private final List<String> allowedIpAddresses;

    @Override
    public Mono<RSocket> accept(ConnectionSetupPayload setup, RSocket sendingSocket) {
        var connection = getPrivateConnection(sendingSocket);
        var remoteAddress = (InetSocketAddress) connection.channel().remoteAddress();
        var clientIpAddress = remoteAddress.getAddress().getHostAddress();
        if (!allowedIpAddresses.contains(clientIpAddress)) {
            throw new IPAddressNotAllowedException(clientIpAddress);
        }
        return delegate.accept(setup, sendingSocket);
    }

    private Connection getPrivateConnection(RSocket rSocket) {
        try {
            var rSocketRequester = FieldUtils.readField(rSocket, "source", true);
            var internalDuplexConnection = FieldUtils.readField(rSocketRequester, "connection", true);
            var tcpDuplexConnection = FieldUtils.readField(internalDuplexConnection, "source", true);
            return (Connection) FieldUtils.readField(tcpDuplexConnection, "connection", true);
        } catch (IllegalAccessException e) {
            throw new IllegalStateException("Can't access connection details!", e);
        }
    }
}
```

It is working because implementation of `io.rsocket.RSocketFactory.ServerRSocketFactory.ServerStart#acceptSetup` contains ` .onErrorResume(err -> sendError(multiplexer, rejectedSetupError(err)).then(Mono.error(err)))` which is propagating error to requester. 

@OlegDokuka can we make getting connection info on setup phase a bit easier?

**Comment by OlegDokuka** [comment]
As I said, it works only because it is TCP based connection. It will not work in case of all other options. The same could be done on the TCP transport setup with no hacks. Use Reactor-Netty TcpServer / TcpClient, provide your connection handler and that is it. DuplexConnection is an abstraction for any Layer 4 transport so exposing API such as address may lead to many unclearnesses.

**Comment by kacper-emersoft** [comment]
I totally agree that this is more hack than target solution. 
I'm using a Spring Boot Reactor Starter in my project and unfortunately I can't see a way to inject my custom connection handler to TcpServer you have mentioned.

**Comment by kacper-emersoft** [comment]
closed by mistake - sorry

**Comment by OlegDokuka** [comment]
@kacper-emersoft we will be exposing the `SocketAddress remoteAddress()` method on the `DuplexConnection` interface, which basically let you check the remote address. 

Once this is going to be done, you will be able to implement a `DuplexConnectionInterceptor` and reject new connections if SocketAddress is not on the list. 

I'm closing this issue in favor of #735, so please track all the updates here.
