### ISSUE TITLE
Gradle Module Metadata for rsocket-bom 1.0.0-RC6 missing from Maven Central / JCenter

### ISSUE THREAD

**Issue by fpavageau** [rsocket/rsocket-java#746]
[`rsocket-bom-1.0.0-RC6.pom`](https://repo1.maven.org/maven2/io/rsocket/rsocket-bom/1.0.0-RC6/rsocket-bom-1.0.0-RC6.pom) was generated with the following comment 
```xml
<!--
 This module was also published with a richer model, Gradle metadata,  
-->
<!--
 which should be used instead. Do not delete the following line which  
-->
<!--
 is to indicate to Gradle or any Gradle module metadata file consumer  
-->
<!--  that they should prefer consuming it instead.  -->
<!--  do_not_remove: published-with-gradle-metadata  -->
```
which triggers the download by Gradle of the `rsocket-bom-1.0.0-RC6.module` artifact, however that artifact was not published to Maven Central or JCenter.

I'm trying to build with Gradle a project using the freshly released Spring Boot 2.2.5, which references `rsocket-bom` `1.0.0-RC6`, and the build fails because of the missing artifact. I'll try to work around that, but the publication should probably be fixed here for the next releases.

**Comment by fpavageau** [comment]
This is probably a consequence of upgrading to Gradle 6 in 4f44695.

**Comment by OlegDokuka** [comment]
fixed by #751

**Comment by kroka** [comment]
Hi, is this really fixed? The module file is also missing for the RC7:

* https://highway.porsche.com/artifactory/maven-all/io/rsocket/rsocket-bom/1.0.0-RC7/

**Comment by spencergibb** [comment]
The fix was to not publish Gradle modules at all if I am not mistaken
