### ISSUE TITLE
WebsocketClientTransport.setTransportHeaders should accept a multimap

### ISSUE THREAD

**Issue by regbo** [rsocket/rsocket-java#753]
Http request headers can be duplicated. For example, a request can send:

[header-name]=[12345]
AND
[header-name]=[abcdefg]

Currently, WebsocketClientTransport.setTransportHeaders accepts a one to one map. I would change it to:

`@Override
  public void setTransportHeaders(Supplier<Map<String, ? extends Iterable<String>>> transportHeaders) {
    this.transportHeaders =
        Objects.requireNonNull(transportHeaders, "transportHeaders must not be null");
  }`

Or create a new method allowing for this

**Comment by rstoyanchev** [comment]
This should be addressed with #844. The `setTransportHeaders` is deprecated in favor of using `Supplier<WebsocketClientSpec.Builder>` or the convenience method `header(String, String...)` method.
