### ISSUE TITLE
Not able to communicate from Java Standalone client to SpringBoot enabled Rsocket server

### ISSUE THREAD

**Issue by dushdushyant** [rsocket/rsocket-java#765]
I have an instance of Rsocket server(responder) and it works perfectly fine when I write a requester snippet out of a springboot API exposed client.
The connection to the server is being established using 
`	private final RSocketRequester rSocketRequester;

	public CustomerServiceAdapter(RSocketRequester.Builder rsocketRequesterBuilder) {
		this.rSocketRequester = rsocketRequesterBuilder
				.connectTcp("localhost", 7000).block();

	}`

This works perfectly when invoked using the **rsc.jar** and command line invocation.
However, when I try to invoke using a standalone Java client as a requester,  there are some issues .The client instance obtained by using 
` RSocket client =
	        RSocketFactory.connect()	 
			.transport(TcpClientTransport.create(7000))
			.start()
			.block();`
RSocketFactory is not able to invoke the server . It connects but an exception with 
_

> MonoIgnoreThen

_ is returned on the client side and the responder server does not listen to the controller mapping and simply **java.nio.channels.ClosedChannelException** is thrown.

Any help would help.

**Comment by OlegDokuka** [comment]
Hey @dushdushyant!

Can you please prepare an example project so I can reproduce it locally?

Cheers,
Oleh

**Comment by dushdushyant** [comment]
Hi Oleg,

Thanks for a prompt reply,
As described above, I have put my code in git.

[https://github.com/dushdushyant/rsocket-server/blob/master/src/main/java/io/pivotal/rsocketserver/RSocketController.java](https://github.com/dushdushyant/rsocket-server/blob/master/src/main/java/io/pivotal/rsocketserver/RSocketController.java)
This is the responder server for RSocket Server and this works fine when tested over the rsc.jar file or another springboot requestor.

The issue is in this code ,
[https://github.com/dushdushyant/rsocket-rnd/blob/master/src/main/java/com/rnd/SampleRScoketClient.java](https://github.com/dushdushyant/rsocket-rnd/blob/master/src/main/java/com/rnd/SampleRScoketClient.java).
This is the requestor code which is trying to create a connection to the Rsocket and invoke a simple message mapping.

Thanks and Regards,
Dushyant

**Comment by rstoyanchev** [comment]
On [this line](https://github.com/dushdushyant/rsocket-rnd/blob/727123925fa4301d9880dca9ba8cd40a145bf8f8/src/main/java/com/rnd/SampleRScoketClient.java#L25), you need to actually subscribe or block for the result. In addition you are providing metadata and data in the wrong order. You also need to think about the data (json, cbor) and metadata ("message/x.rsocket.routing.v0") encoding. 

Basically when you drop down on this level you have a lot more to think about.

**Comment by dushdushyant** [comment]
Thanks for the feedback,
any reference to a working example of that would be helpful.

**Comment by making** [comment]
@dushdushyant 
Here is my example from [vanilla rsocket client](https://github.com/making/demo-rsocket/blob/master/vanilla-rsocket-client/src/main/java/com/example/vanillarsocketclient/VanillaRsocketClientApplication.java) to [spring boot rsocket server](https://github.com/making/demo-rsocket/blob/master/demo-rsocket-server/src/main/java/com/example/rsocket/GreetingController.java).
Hope this helps you.
