### ISSUE TITLE
Refactors RSocketFactory API

### ISSUE THREAD

**Issue by OlegDokuka** [rsocket/rsocket-java#772]
This issue stands for better API

1) Refactors keepAlive setup to the builder. Old API should be deprecated

```
ClientRSocketFactory keepAlive(KeepAlive spec);

KeepAlive.of(Duration tickInterval, Duration timeout);

KeepAlive.builder()
             .missedAcks(int number)
             .ackTimeout(Duration ackTimeout)
             .build();
```

2) Refactor Ressumability API to the builder in the same fashion as keepAlive. Also, a related issue to that is #766 

3)Possibly, not sure it would make sense but: Refactors Setup API to the builder:

```
setupPayload(
   SetupSpec.builder()
            .dataMimeType(...)
            .metedataMimeType(...)
            .payload(Payload)
)
```

**Comment by rstoyanchev** [comment]
Some extra, initial thoughts:
- keepAlive - there are 4 methods but underneath it boils down to two values, so this could be simplified to reduce the options and also align with the spec terminology (e.g. `keepAliveTimeBetweenFrames` and `keepAliveMaxLifeTime`). 
- resume - there are about 6 methods for the client and 5 for the server. There is a case for some sort of `Resume` spec (similar to the new [Retry](https://projectreactor.io/docs/core/release/api/reactor/util/retry/Retry.html) in Reactor).
- possibly other smaller opportunities - e.g. do we really need `mimeType` or 3 acceptor options on the client side..

**Comment by rstoyanchev** [comment]
I think we can close this one in favor of #778.
