### ISSUE TITLE
RSocketFactory API Enhancements

### ISSUE THREAD

**Issue by rstoyanchev** [rsocket/rsocket-java#778]
After #770 and #774 we are left with:
![remaining](https://user-images.githubusercontent.com/401908/78998658-f498cf00-7b40-11ea-9c84-db234e6a4956.png)

This is better (see #770 for the starting point) but a 10 package tangle is not ideal. Fortunately it is mainly due to top-level `RSocketFactory` referencing companion contracts from feature sub-packages which in turn refer back to `io.rsocket`. If `RSocketFactory` was in `core` we get tangle free package structure:

![tangle-free](https://user-images.githubusercontent.com/401908/78999044-bea81a80-7b41-11ea-929b-6d27446cb7b0.png)

In order to evolve to this, we can deprecate the existing `RSocketFactory` in `io.rsocket`, add a replacement in `io.rsocket.core` and make the existing one a smiple delegate to the new one. That will allow a period of migration for existing libraries and applications.
 
This is also an opportunity to re-think the existing `RSocketFactory` API which has grown a lot and can be improved in quite a few ways. Doing so would provide additional value to switch from the deprecated to the new API.

A few possibilities to explore:

- Replace `RSocketFactory.ClientRSocketFactory` and `RSocketFactory.ServerRSocketFactory` with dedicated client vs server types, e.g. `RSocketConnector` and `RSocketServer`.
- Rename "plugin" registration methods to match the "interceptor" terminology that's now used everywhere else; add ways to register interceptors at a specific index (e.g. via `Consumer<List<...>>`); add `InterceptorConfigurer` so there is only one top-level method related to interception of any kind.
- keepAlive - there are 4 methods but underneath it boils down to two values, so this could be simplified to reduce the options and also align with the spec terminology (e.g. keepAliveTimeBetweenFrames and keepAliveMaxLifeTime).
- resume - there are about 6 methods for the client and 5 for the server. There is a case for some sort of `Resume` spec (similar to the new Retry in Reactor).
- review all else - e.g. do we really need mimeType or 3 acceptor options on the client side..

**Comment by OlegDokuka** [comment]
Mirroring what I said in #772 

Refactors keepAlive setup to the builder. Old API should be deprecated
ClientRSocketFactory keepAlive(KeepAlive spec);

KeepAlive.of(Duration tickInterval, Duration timeout);

KeepAlive.builder()
             .missedAcks(int number)
             .ackTimeout(Duration ackTimeout)
             .build();
Refactor Ressumability API to the builder in the same fashion as keepAlive. Also, a related issue to that is #766
3)Possibly, not sure it would make sense but: Refactors Setup API to the builder:

setupPayload(
   SetupSpec.builder()
            .dataMimeType(...)
            .metedataMimeType(...)
            .payload(Payload)
)
