### ISSUE TITLE
package io.rsocket.core does not exist during maven build

### ISSUE THREAD

**Issue by mikayeln** [rsocket/rsocket-java#790]
Hello.

I'm facing some strange problem.
During maven build I'm getting `package io.rsocket.core does not exist`.
My pom.xml contains following dependencies

```
       <dependency>
            <groupId>io.rsocket</groupId>
            <artifactId>rsocket-core</artifactId>
            <version>1.0.0-RC6</version>
        </dependency>

        <dependency>
            <groupId>io.rsocket</groupId>
            <artifactId>rsocket-transport-netty</artifactId>
            <version>1.0.0-RC6</version>
        </dependency>
```

Analyzing rsocket-core jar file showes that there is no core package in that jar. Did I missed some dependencies?

Thanks

**Comment by OlegDokuka** [comment]
Hi @mikayeln!

`.core` the package exists starting from RC-7

Cheers,
Oleh

**Comment by mikayeln** [comment]
Thanks for the quick reply, @OlegDokuka.
So what about an example of TrivialClient? I need 1.0.0-RC7 to build? I just don't see RC7 in maven-central.

**Comment by OlegDokuka** [comment]
@mikayeln Please use snapshot repo for now in order to access RC7-SNAPSHOT (https://oss.jfrog.org/artifactory/oss-snapshot-local/io/rsocket/rsocket-bom/1.0.0-RC7-SNAPSHOT/). 
In general, we are about to release, you will get it soon

Cheers,
Oleh
