### ISSUE TITLE
Parsing Strictness

### ISSUE THREAD

**Issue by benjchristensen** [rsocket/rsocket-java#8]
Right now it fails if it sees a message it doesn't understand: https://github.com/ReactiveSocket/reactivesocket-java/blob/e38b757ca02e597712139dfb9d01ba5dc7079c40/src/main/java/io/reactivesocket/ReactiveSocketServerProtocol.java#L76 

Should this continue to behave this way? Are there message types it should ignore?

The protocol will support headers with an "ignore" bit: https://github.com/ReactiveSocket/reactivesocket/blob/79b046b3617a28ee5809f988967acc2b4ea3541c/Protocol.md#header-chains This suggests the server should at least ignore those if it doesn't understand them.

**Comment by tmontgomery** [comment]
The ignore bit for headers will allow new headers to be added without breaking old behavior.

But there is a deeper question around correctness and handling the unexpected.

For example, what is the correct behavior for a Responder when it receives a REQUEST_STREAM for a stream ID it is currently processing and sending NEXTs for? Should it ignore it? ERROR the stream? etc.

**Comment by benjchristensen** [comment]
I don't think we've consciously done anything with this in the java impl.

**Comment by tmontgomery** [comment]
Not yet, no. Probably should add it, though.

**Comment by yschimke** [comment]
Going to close this issue, I think the protocol should drive this sort of work.
