### ISSUE TITLE
Unmarshal problem for CompositeMetadata with NOT wellknown MIME type.

### ISSUE THREAD

**Issue by jjeffcaii** [rsocket/rsocket-java#810]
Hi~

I made a CompositeMetadata in golang SDK (according to: https://github.com/rsocket/rsocket/blob/master/Extensions/CompositeMetadata.md), but sadly it decoded failed in java.

Is there some wrong in `io.rsocket.metadata.CompositeMetadataFlyweight` line 94?
After removing `+1`, it can be decoded successfully.

```java
        // M flag unset, remaining 7 bits are the length of the mime
        int mimeLength = Byte.toUnsignedInt(mimeIdOrLength) + 1;

// I think it should not plus 1.
//  int mimeLength = Byte.toUnsignedInt(mimeIdOrLength);
```

Here's my raw CompositeMetadata bytes and unit tests.

```java
  @Test
  public void test() {
    String s =
        "/gAAFhVzdHVkZW50LnYxLm5vb3AuaGVsbG8qbWVzc2FnZS94LnJzb2NrZXQuYXV0aGVudGljYXRpb24uYmVhcmVyLnYwAAAWdGVzdCB1bmtub3duIG1pbWUgdHlwZQ==";
    byte[] raw = Base64.getDecoder().decode(s);
    ByteBuf bb = Unpooled.copiedBuffer(raw);
    CompositeMetadata cm = new CompositeMetadata(bb, false);
    cm.stream()
        .forEach(
            entry -> {
              System.out.println(
                  entry.getMimeType()
                      + ": "
                      + entry.getContent().toString(StandardCharsets.US_ASCII));
            });
  }
```

**Comment by jjeffcaii** [comment]
Oops... I found some codes when encode metadata header. I guess that is what causes my problem. 囧rz

`CompositeMetadataFlyweight.java`,  Line 351:

```java
    // go back to beginning and write the length
    // encoded length is one less than actual length, since 0 is never a valid length, which gives
    // wider representation range
    metadataHeader.writerIndex(writerIndexInitial);
    metadataHeader.writeByte(customMimeLength - 1);
```

Maybe we should add it to the protocol SPEC. :-D

**Comment by OlegDokuka** [comment]
Hey @jjeffcaii!

I guess spec is clear on that

```
Metadata Encoding MIME Type: MIME Type for encoding of Metadata. This SHOULD be a US-ASCII string that includes the Internet media type specified in RFC 2045. Many are registered with IANA and others such as Routing and Tracing (Zipkin) are not. Suffix rules MAY be used for handling layout. The string MUST NOT be null terminated. (Not present if M flag is set)
```

the most important from there is 
`The string MUST NOT be null terminated. (Not present if M flag is set)`
which basically means that custom mime type can not be 0 length, thus we can consider 0 as 1 in order to expand encoded string length.

Do you think it is necessary to mention that 
`If M flag is not set, indicates the encoding MIME Type Length in bytes. MIME Type Length MUST be > 0`? if it is derivable from `The string MUST NOT be null terminated`?

**Comment by jjeffcaii** [comment]
@OlegDokuka Thanks! 👍 
My mistake, I'll fix my implementation. 😂

**Comment by simonbasle** [comment]
Just a side note: I agree that these corner case would benefit from being documented VERY explicitly in the spec, as I remember I had to double check and triple check when implementing the spec in java.
