### ISSUE TITLE
Interaction between RSocket onClose and dispose

### ISSUE THREAD

**Issue by jkschneider** [rsocket/rsocket-java#819]
In 1.0.0-RC7 it seems like for `onClose()` to be subscribable, we have to do something with the "error" resulting from the `dispose()` that previously was not required. This is a _passing_ test written in `RSocketTest` that demonstrates what seems to be required:

```java
@Test
public void disposeAndOnClose() throws InterruptedException {
  CountDownLatch latch = new CountDownLatch(1);
  rule.crs.onClose()
          .map(v -> 1)
          .onErrorReturn(1) // I only care to know that it was closed, not why
          .subscribe(closed -> latch.countDown());
  rule.crs.dispose();

  assertThat(latch.await(1, TimeUnit.SECONDS)).isTrue();
}
```

Otherwise you get the exception:

```
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.concurrent.CancellationException: Disposed
Caused by: java.util.concurrent.CancellationException: Disposed
	at io.rsocket.core.RSocketRequester.lambda$dispose$1(RSocketRequester.java:188)
	at io.rsocket.core.RSocketRequester.tryTerminate(RSocketRequester.java:690)
	at io.rsocket.core.RSocketRequester.dispose(RSocketRequester.java:188)
```

I did the weird `map(v -> 1).onErrorReturn(1)` thing because for the latch to count down we need a non-empty `Mono<Void>`, but paradoxically cannot create a `Mono<Void>` with null, the only valid value for `Void`. I'm probably just not seeing how to do this more idiomatically.

**Comment by rstoyanchev** [comment]
This is shutting down cleanly for me in RC7:
https://github.com/benwilcock/spring-rsocket-demo/blob/a9957ba5caecfb21fb5753e9e582d8ee17ba6294/rsocket-client/src/main/java/io/pivotal/rsocketclient/RSocketShellClient.java#L52-L53

In other words, just `onClose().doFinally(..).subscribe()`.

**Comment by rstoyanchev** [comment]
but I suppose the key is to wait..

**Comment by jkschneider** [comment]
@rstoyanchev I think only because you have the `doOnError` [right above it](https://github.com/benwilcock/spring-rsocket-demo/blob/a9957ba5caecfb21fb5753e9e582d8ee17ba6294/rsocket-client/src/main/java/io/pivotal/rsocketclient/RSocketShellClient.java#L51). I've observed that `doOnError` has the same effect as a `onErrorReturn`, etc. 

Prior to RC7, I had an `onClose()` without either of these and everything was working fine. It started breaking in RC7.

* Working code pre-RC7 is [here](https://github.com/micrometer-metrics/prometheus-rsocket-proxy/blob/v0.10.6/client/src/main/java/io/micrometer/prometheus/rsocket/PrometheusRSocketClient.java#L115).
* Workaround for RC7 is [here](https://github.com/micrometer-metrics/prometheus-rsocket-proxy/blob/master/client/src/main/java/io/micrometer/prometheus/rsocket/PrometheusRSocketClient.java#L115-L117).
