### ISSUE TITLE
Enhancement - Client/Server Routing and Function Mapping

### ISSUE THREAD

**Issue by regbo** [rsocket/rsocket-java#823]
I've used RSocket in a few projects now, and we always seem to spend a lot of time with:

- Routing payloads on the server side
- Serializing payloads to interact with legacy code

I know there's Netifi and other protobuf rpc projects, but a lot of them seem like overkill to improve the above. 

I created a simple library that aids in some of this by allowing routable "handlers" to be added to server rSockets. Basically the handlers are functions that return empty optionals if they can't handle a request.

I also added in the ability to map a client router to muliple client RSockets. This allows for functions to brodcast to mutiple clients easily.

The code required is very simple and is mostly added to expanded interfaces. I think a lot of it would make sense in the official RSocket project.

Alternatively perhaps this is achievable with the native client?

Have a look here:
https://github.com/regbo/lfp-rsocket-router

**Comment by OlegDokuka** [comment]
Hi @regbo!

Thanks for sharing your project. We have RSocket-RPC-Java which has an IPC module that does the same. (https://github.com/rsocket/rsocket-rpc-java/blob/master/rsocket-ipc-core/src/main/java/io/rsocket/ipc/IPCRSocket.java). Feel free to contribute if you think it can be improved.


Cheers,
Oleh

**Comment by regbo** [comment]
AH! I saw thought that project only used protobuf, and i missed the IPC subproject.

Oops. Thanks!

**Comment by spencergibb** [comment]
Also https://github.com/rsocket-routing
