### ISSUE TITLE
Symmetric SocketAcceptor on both client and server is prone to deadlock

### ISSUE THREAD

**Issue by mostroverkhov** [rsocket/rsocket-java#841]
#676 introduced client/server `SocketAcceptor` of same form `(SetupFrame, RequesterRSocket) -> Mono<HandlerRSocket>`, which deadlocks RSocket if *both* acceptors do e.g.
`return RequesterRSocket.requestResponse(Payload).map(Payload -> HandlerRSocket)`. `SocketAcceptor` could be of form `(SetupFrame, RequesterRSocket) -> HandlerRSocket` on both sides (symmetric), with server signature `(SetupFrame, RSocketRequester) -> Mono<SocketAcceptor>`, and client signature just `(SetupFrame, RSocketRequester) -> SocketAcceptor` - as only server is able to reject requests

**Comment by OlegDokuka** [comment]
Hey @mostroverkhov.

Can you please provide an example that can reproduce that issue?

**Comment by rstoyanchev** [comment]
@mostroverkhov, the symmetric `SocketAcceptor` was meant to allow 3rd party components like Spring Security to get access to connection setup info from either side. The name `SocketAcceptor` is certainly a stretch from the client side, and something like `ConnectionHandler` would be more fitting I think.

That said I don't see why both client and server shouldn't be able to do something async before starting to respond. I see the `Mono<RSocket>` return value as less about accepting and more about doing something at the start. Theoretically, even from the client side, a 3rd part component might have reasons to preclude the connection by returning an error.

It is indeed an issue if both sides want to get a response from the remote before starting to respond, but are there good reasons for that? I can't think of a case and I'd rather consider ways to change the API to make it clear, that handling the providing the responding `RSocket` should be independent of using the sending `RSocket`.

**Comment by rstoyanchev** [comment]
Closing for now as there are no plans for immediate changes.
