### ISSUE TITLE
requestChannel(Payload, Publisher<Payload> ) is more reasonable

### ISSUE THREAD

**Issue by xy02** [rsocket/rsocket-java#875]
I think the method signature ***requestChannel(Publisher<Payload> payloads)*** of the interface **io.rsocket.RSocket** does not match RSocket Protocol, and ***requestChannel(Payload requestPayload, Publisher<Payload> payloads)*** make sense.
A possible scenario:
```
Flux<Payload> requestChannel(Payload videoTranscodingSetting, Publisher<Payload> videoChunks){
    //do some transcoding
}
```

**Comment by yschimke** [comment]
Closing as a duplicate.

Relevant previous discussions

https://github.com/rsocket/rsocket-java/issues/465
https://github.com/rsocket/rsocket-java/issues/569
https://github.com/rsocket/rsocket-java/issues/762
