### ISSUE TITLE
Update reactor-bom to Dysprosium-SR9

### ISSUE THREAD

**Issue by artem-v** [rsocket/rsocket-java#879]
Reactor netty 0.9.9 (Dysprosium-SR9) has important fix which covers fd leaks. 

https://github.com/reactor/reactor-netty/releases/tag/v0.9.9.RELEASE
Fix to file descriptor leak: ([#1152](https://github.com/reactor/reactor-netty/issues/1152), [#1154](https://github.com/reactor/reactor-netty/pull/1154), [#1163](https://github.com/reactor/reactor-netty/issues/1163))

**Comment by OlegDokuka** [comment]
superseded by #889
