### ISSUE TITLE
Customize `RSocketRequester` serial scheduler in `RSocketServer`

### ISSUE THREAD

**Issue by jg513** [rsocket/rsocket-java#892]
https://github.com/rsocket/rsocket-java/blob/92afb38ac6fc98f66c0e6d4c073377c790b9c127/rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java#L437

How to change the serial scheduler?

From:
```java
Schedulers.single(Schedulers.parallel())
```
To vert.x scheduler:
```java
Schedulers.fromExecutor(command -> vertx.runOnContext(v -> command.run()))
```

**Comment by OlegDokuka** [comment]
@jg513 Scheduler is not designed to be a public API and is removed as of 1.1.x.

Nevertheless, you can always customize the global Reactor `SchedulerFactory` using [`Schedulers.setFactory`](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java#L705) method.

**Comment by jg513** [comment]
Thanks, that solved my problem.
