### ISSUE TITLE
RSocket server is subject to frames flood for non-existent streams

### ISSUE THREAD

**Issue by mostroverkhov** [rsocket/rsocket-java#898]
RSocket server indefinitely accepts PAYLOAD frames of [non-existent](https://github.com/rsocket/rsocket-java/blob/b3d823c262e04e4965f9c3aae41a6a64719aafd9/rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java#L331) (terminated) streams. This can be abused by rogue clients to degrade server's responsiveness and increase operational costs.

Local testing with *single* client continuously sending 1k bytes frames over 1000 mbit connection showed that generated traffic consumed up to 10% (server process) of 12 vCPU  box.

Issue is similar to [[1](https://github.com/rsocket/rsocket-java/issues/895)], except that payload frames of up to 16 MBytes (RSocket frame size limit) can be used.

**Comment by OlegDokuka** [comment]
I see a possible improvement in `ClientServerMultiplexer` so we can get rid of few `volatile` read/writes. 

But my belief is that a user should put an interceptor to track such attack and protect against it and rsocket implementation should not bring any assumption on how to detect such an attack.

As an improvement, we can consider exposing existing streams in readonly mode, to let interceptor do track of existing streams and detect frames for non-existing. The same tracking can be done independently though, so an interceptor will be mimic the same as internals in RSocket do.

I will try to play around to see if one can protect agains it without touching internals

**Comment by rstoyanchev** [comment]
@mostroverkhov do you have any suggestions for what we can do? From the perspective of RSocket Java, such frames are dropped and probably couldn't be dropped much earlier to make a substantial difference. Any other solution requires keeping track of how many frames have been received for non-existent streams and choosing a threshold will be difficult without more knowledge of the application.
