### ISSUE TITLE
Reconnect after server restart

### ISSUE THREAD

**Issue by uselvvi** [rsocket/rsocket-java#900]
Dear RSocket team,

First of all, I am playing with rsocket. It looks great so far. This is more of a question. 
This is a very simple spring boot service class for rsocket client. As you see we establish rsocket connection as part of constructor, cache the requestorMono. The below code works perfectly fine as long as server is not restarted. When you restart server, the connection is broken. Client needs to be restarted to make this work. The `retry` in the ping chain will NOT help as it is cached already. Is there any built in approach in rsocket to handle this? 

```
@Service
public class RSocketPingService {

    private final Mono<RSocketRequester> requesterMono;

    // Spring Boot is creating an auto-configured RSocketRequester.Builder bean
    public RSocketPingService(RSocketRequester.Builder builder) {
        this.requesterMono = builder
                .dataMimeType(MediaType.APPLICATION_CBOR)
                .connectTcp("localhost", 7000).retry(5).cache();
    }

    public Mono<String> ping() {
        return this.requesterMono.flatMap(requester -> requester.route("pong")
                .data("TEST")
                .retrieveMono(String.class));
    }

}
```

**Comment by OlegDokuka** [comment]
Hello @uselvvi!

It is great to get more users on board!

Have you looked at build-in [reconnect](https://github.com/rsocket/rsocket-java/blob/master/rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java#L374) feature which does exactly what you need:


```java

@Service
public class RSocketPingService {

    private final Mono<RSocketRequester> requesterMono;

    // Spring Boot is creating an auto-configured RSocketRequester.Builder bean
    public RSocketPingService(RSocketRequester.Builder builder) {
        this.requesterMono = builder
                .rsocketConnector(connector -> connector.reconnect(Retry.backoff(10, Duration.ofMillis(500)))
                .dataMimeType(MediaType.APPLICATION_CBOR)
                .connectTcp("localhost", 7000);
    }

    public Mono<String> ping() {
        return this.requesterMono.flatMap(requester -> requester.route("pong")
                .data("TEST")
                .retrieveMono(String.class));
    }

}

```

**Comment by uselvvi** [comment]
Thanks @OlegDokuka for clarifying. It works great!
I see what you have done. My confusion now is - will it not connect to the server for every request? Will it not become like HTTP?

**Comment by OlegDokuka** [comment]
@uselvvi nope. Reconnect works only on the connection level. It means that given `Mono<RSocket>` caches a last resolved rsocket which is working and shares it between all new subscribers until it this instance becomes disposed (frankly speaking until the underlying connection is closed). 

Once the RSocket goes away, the Mono will have no instance, so once it gets a new subscriber interested in the RSocket, it will try to resolve a new instance

**Comment by uselvvi** [comment]
Awesome!! Thanks @OlegDokuka

**Comment by nbabic298** [comment]
Hi @OlegDokuka ,

I'm using the same code as you mentioned and have @ConnectMapping method on the server side. It seems RSocket is not cached because on each request that connect method gets invoked. 

Putting .cache() after .connectTcp("localhost", 7000) works (i.e. connect method is only invoked once) but on server restart reconnect doesn't work (ClosedChannelException).

I'm using Spring Boot 2.3.0.Release, do you have some ideas what could be the problem or is this expected beahviour?

Tnx

**Comment by OlegDokuka** [comment]
@uselvvi did you use the `reconnect` I mentioned earlier (no need to use cache at all)

**Comment by nbabic298** [comment]
Tnx for answering, yes I used reconnect, here is my client code:

`@Slf4j
@RestController
public class TestController {

    private Mono<RSocketRequester> deviceRSocketRequester;

    public TestController(RSocketRequester.Builder deviceRSocketRequesterBuilder, RSocketProps rsocketProps) {
        this.deviceRSocketRequester = deviceRSocketRequesterBuilder
                .dataMimeType(MimeTypeUtils.APPLICATION_JSON)
                .rsocketConnector(connector -> {
                    connector.reconnect(Retry.fixedDelay(100L, Duration.ofSeconds(5L)));

                })
                .connectTcp(rsocketProps.getDevice().getHostname(), rsocketProps.getDevice().getPort());
    }

    @GetMapping("test/{word}")
    public Mono<Void> testRsocket(@PathVariable String word) {
        log.info("Calling RC with data: " + word);
        return callRc(word);
    }

    public Mono<Void> callRc(String word) {
        return deviceRSocketRequester.flatMap(req -> req.route("test")
                .data(word)
                .retrieveMono(Void.class))
                .doOnError(error -> {
                    log.error("Error: {}", error.getClass());
                });
    }

}`

And here is the server code:

`@Slf4j
@Controller
public class TestApiController {

    @MessageMapping("test")
    public Mono<Void> testRsocket(String word) {
        log.info("Word on the street is: " + word);
        return Mono.empty();
    }

    @ConnectMapping
    public Mono<Void> connect(RSocketRequester requester) {
        log.info("Client Connected!", requester.rsocket().availability());
        return Mono.empty();
    }

}`

Each time I invoke client's callRc() method the server's connect method gets invoked, should this happen?

**Comment by vinsguru** [comment]
This behavior seems to be correct to me. As **_@ConnectMapping_** is supposed to be invoked for every rsocket request. This is not client-server connection establishment. it is for request level.

**Comment by nbabic298** [comment]
> This behavior seems to be correct to me. As **_@ConnectMapping_** is supposed to be invoked for every rsocket request. This is not client-server connection establishment. it is for request level - for streaming messages,it will be invoked once.

Thanks for the explaination, just one more thing if I put `.cache()` after the `connectTcp(..)` then connect method gets called only once and `testRsocket()` method ouputs log statements as many times as I call it from client. Do you have some reasoning what happens in that example? Does that make a request stream or something like that?

**Comment by vinsguru** [comment]
@nbabic298 My bad. I had deleted my comment immediately as I did not read your question clearly. I did not realize that you responded too soon.

Can you check here? We do not need cache.If you add @ConnectMapping, for every request it will be invoked once the setup is complete.

https://github.com/vinsguru/vinsguru-blog-code-samples/tree/master/rsocket/spring-rsocket

**Comment by vinsguru** [comment]
@nbabic298  I just checked the SO answer as well. It seems to match with what I have in this repo as well. Check your version. I use 2.3.2.RELEASE.
