### ISSUE TITLE
RSocket - Support for Flux in Mono out

### ISSUE THREAD

**Issue by vinsguru** [rsocket/rsocket-java#907]
Dear All,
Thank you so much for all your contribution!

Have a question / suggestion.

**Server side:**

I have a rsocket server which accepts `Flux<Payload>` and returns a `Mono<Status>`.

**Client side:**

Even though I return from a Mono server, this works perfectly fine and totally ok.
```
@Autowired
private Mono<RSocketRequester> rSocketRequester;


this.rSocketRequester
    .map(r -> r.route(......)
                     .data(Flux.fromIterable(list))
    )
    .flatMapMany(r -> r.retrieveFlux(Status.class));
```

But If I switch to Mono, It does not work!
```
this.rSocketRequester
    .map(r -> r.route(......)
                     .data(Flux.fromIterable(list))
    )
	.flatMap(r -> r.retrieveMono(Status.class));  // This is not working and I get below exception.
```

```
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IllegalStateException: No RSocket interaction with Flux request and Mono response.
Caused by: java.lang.IllegalStateException: No RSocket interaction with Flux request and Mono response.
	at org.springframework.util.Assert.state(Assert.java:76) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.messaging.rsocket.DefaultRSocketRequester$DefaultRequestSpec.getPayloadMono(DefaultRSocketRequester.java:306) ~[spring-messaging-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.messaging.rsocket.DefaultRSocketRequester$DefaultRequestSpec.retrieveMono(DefaultRSocketRequester.java:268) ~[spring-messaging-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.messaging.rsocket.DefaultRSocketRequester$DefaultRequestSpec.retrieveMono(DefaultRSocketRequester.java:258) ~[spring-messaging-5.2.8.RELEASE.jar:5.2.8.RELEASE]
```
Why do we not explicitly support Mono here? Can we make it generic by returning a `Publisher<Payload>` instead of Flux specifically.?

`default Flux<Payload> requestChannel(Publisher<Payload> payloads)
`

**Comment by OlegDokuka** [comment]
@vinsguru This is not a vanilla RSocket-Java issue. Please consider submitting it to the https://github.com/spring-projects/spring-framework/ repo

@rstoyanchev can you please transfer that one if possible?

**Comment by bclozel** [comment]
This was already submitted as spring-projects/spring-boot#22713

@vinsguru As explained in the issue above, Spring Framework is merely [mapping the RSocket interactions at the API level](https://github.com/rsocket/rsocket/blob/master/Protocol.md#stream-sequences-and-lifetimes). We can't really support a `Mono` there without:
1. a new interaction model
2. or buffering all elements before emitting it

In our case, 1) can only be achieved by adding a new interaction model - and I don't think this is the way forward. 2) can only be achieved in your own codebase with a `collect*` operator on `Flux`. Since this is a very specific concern, I don't think can properly support that in Spring Framework for all use cases.

**Comment by vinsguru** [comment]
@bclozel 

I thought It could be a valid use case for the responder to send just a single respond for the request stream. Might be a bad example. but consider this. Responder could be a calculator app for which client sends 1, 2, 3, 4 - a stream of request to the '+' message mapping. Upon sending '=', the responder might send final result of `Mono<10>`.

It works fine with the workaround anyway as I had stated above. Please feel free to close this.

**Comment by rstoyanchev** [comment]
@vinsguru as @bclozel mentioned there are 4 interaction models in RSocket. In Spring you don't have to name the interaction, just use `Mono` and `Flux`, but one of those models has to be chosen on the wire. 

Now we could allow Flux in and Mono out, perform a request-channel interaction and then `.take(1)` on the response but the idea is to avoid cases where the framework has to potentially drop or ignore further messages. The application should be more explicit in making requests that correspond to the available interaction models and then explicitly ignore any extra data it does not expect. So for this case, use Flux in and Flux out and add `.take(1)` or `.next()`.

Note that in some cases this kind of lenience, if allowed, can lead to a mismatch in interaction models. For example requester is Mono-to-Mono while responder is Mono-to-Flux. This would become a request-response on the wire and if the server allowed that to be matched to a Mono-to-Flux method, it would have to ignore all response messages after the first with the requester possibly not even being aware that it is a request-stream interaction. You can see the cardinality rules for `@MessageMapping` methods in the [Spring Framework docs](https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#rsocket-annot-messagemapping).

**Comment by vinsguru** [comment]
@rstoyanchev Understood now. Thanks for the explanation.
Closing this.

Thank you all for your contribution to the open source community.
