### ISSUE TITLE
RSocket Request Stream hangs when connection per request is used on load test

### ISSUE THREAD

**Issue by kprasad99** [rsocket/rsocket-java#911]
Trying to replace `GRPC` with `RSocket` for my inter microservice communication which shall be deployed in kubernetes. Since its
inside kubernetes I'm not using client side loadbalancer(which `rsocket-java` provides) as it doesn't fit well with Horizontal Pod Autoscale. For the same reason I'm using connections per request, so that requests can be distributed among pods/instances rather than rsocket client connect to same server(at boot time) and share the connection for all request.

## Use case
I've create two demo MS `person-service` and `person-db-service`, `person-db-service` acts as Backend that serves person information form H2 DB, with rsocket server endpoint using spring's `@MessageMapping` to serve the for other Micro serivce. `person-service` has a `flux` based rest endpoint `/api/rsoc/person` which internally uses `rsocket client` to connect to `rsocket server` at `person-db-service`. RSocket encoding is `protobuf` and protocol type is `request-stream`.

Now Load test the above setup using `fortio` with configuration `QPS=1000,duration=3m,threads-8`.  

## Expected Behavior
Expected a performance metrics better than `GRPC` if not atleast same level.  Since have installed `BlockHound` if there is any thread contention issue it should print thread stack trace.

## Actual Behavior
The requests starts hanging after 10-15s, with all request timing out, I reduced the above configuration  `QPS=50,duration=3m,threads-2`. it started failing after 25s and I further reduced to `QPS=10,duration=3m,threads-2`, now it hangs after `1m`. If I try to access the endpoint after load test I get below error.
```java

reactor.netty.internal.shaded.reactor.pool.PoolAcquireTimeoutException: Pool#acquire(Duration) has been pending for more than the configured timeout of 45000ms
	at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.run(AbstractPool.java:346) ~[reactor-netty-0.9.10.RELEASE.jar:0.9.10.RELEASE]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler io.github.kprasad99.endpoint.PersonRsocService#list() [DispatcherHandler]
	|_ checkpoint ⇢ org.springframework.cloud.sleuth.instrument.web.TraceWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP GET "/api/rsoc/person" [ExceptionHandlingWebHandler]
Stack trace:
		at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.run(AbstractPool.java:346) ~[reactor-netty-0.9.10.RELEASE.jar:0.9.10.RELEASE]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.3.8.RELEASE.jar:3.3.8.RELEASE]
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
		at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

```  

## Steps to Reproduce

The code base is upload [github](https://github.com/kprasad99/k8s-rsocket-protobuf) and have mentioned to start the application. Below is the steps I used to start fortio docker 

```sh
docker run -p 18080:8080 -p 8079:8079 fortio/fortio server
```
once fortio is started, wen to browser and opened url `http://localhost:18080/fortio` and configured above said configurations and run load test.

Sample Rsocket client configuration

```java
@Configuration
@EnableConfigurationProperties(PersonServiceProperties.class)
public class RsocektClientConfig {

    @Bean
    Mono<RSocketRequester> rSocketRequester(RSocketRequester.Builder rsocketRequesterBuilder,
            RSocketStrategies strategies, PersonServiceProperties props) {

        return Mono.defer(() -> rsocketRequesterBuilder.rsocketStrategies(strategies)
                .dataMimeType(new MimeType("application", "x-protobuf"))
                .connectTcp(props.getHost(), props.getPorts().getRsocket()));

    }

    @Bean
    public RSocketStrategiesCustomizer protobufRSocketStrategyCustomizer() {
        return (strategy) -> {
            strategy.decoder(new ProtobufDecoder());
            strategy.encoder(new ProtobufEncoder());
        };
    }

}
```

RSocketClient.java
```java
@Service
public class PersonRSocketClient {

	@Autowired
	private Mono<RSocketRequester> resocketRequester;

	public Flux<Person> list() {
		return resocketRequester.flatMapMany(r -> r.route("io.github.kprasad99.person.list").retrieveFlux(Person.class));
	}

	public Mono<Person> findById(int id) {
		return resocketRequester.flatMap(r -> r.route("io.github.kprasad99.proto.person.id")
				.data(id).retrieveMono(Person.class));
	}

}
```

NOTE: If I use `RSocketRequester resocketRequester` it works however request lands into same instance, which I want to avoid.

## Environment

* RSocket version(s) used: 1.0.1
* RSocket transport netty version: 1.0.1
* Spring Boot: 2.3.2.RELEASE
* spring-webflux: 5.2.8.RELEASE:
* Platform (eg. JVM version (`javar -version`) or Node version (`node --version`)): JRE-11
* OS and version (eg `uname -a`): Ubuntu.20.04

**Comment by OlegDokuka** [comment]
Hi @kprasad99!

Thanks for asking that.

### First of all, RSocket is not designed to be used in the `request per connection` fashion and we are  not planning to tune RSocket for such usage approach at any point in time

### Secondly, we highly recommend using client-side load balancing since it does not prevent one to integrate it with Kubernetes service discovery.

### Thirdly, if non of the approaches fits the use-case, we recommend switching to normal HTTP usage

**Comment by rstoyanchev** [comment]
@kprasad99 a couple of extra pointers. One, the Loadbalance api is getting updated and improved in 1.1. Two, here is an example based on the new API that shows [periodically obtaining](https://github.com/rsocket/rsocket-java/blob/master/rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/loadbalancer/RoundRobinRSocketLoadbalancerExample.java) a list of hosts to use which could be obtained from any source.
