### ISSUE TITLE
Is it possible to send data in parallel in server using the same requester from client

### ISSUE THREAD

**Issue by KaimingWan** [rsocket/rsocket-java#921]
Rsocket support full duplux and peer to peer communication as far as I know. After client has connected to server, we can get the RSocket object to send data from server proactively. Here comes a case that we have parallel request to send data in the server side. All the parallel request will use the same RSocket which is stored in menory when the client connect to server.

I have checked issue #868 and the example code class TaskProcessingWithServerSideNotificationsExample. Actually, I did the same thing in server side like the example. I maintain a map in memory to store the RSocket object that is used to send data to client. However, in my case, there have parallel request need to send to client proactively in the server side. I find that the late server side's request will cause the previous request fail which is on the same RSocket object. In the parallel case, all the server side rsocket request will fail. Now I add lock to avoid competition on the same rsocket object, all the parallel server side requests now are executed in serial and the functionality works well. In consequence of this, the performance is very poor. Is there exists some way to solve the case?

**Comment by OlegDokuka** [comment]
Hi @KaimingWan 

Do you have any code sample?

Cheers,
Oleh

**Comment by KaimingWan** [comment]
@OlegDokuka Thanks for your reply.  I am sorry that my code is highly integrated with biz code and denpend on spring-rsocket, so it is not convient now to extract them as an rsocket-java example. However, your reply solve my confusion. Before ask the question, I also think that we can't parallel request on the single connection. Your reply strengthened my mind. Maybe let the client create serveral connections and maintain a connection pool in the server side will enable send request to the client in parallel. What do you think?

**Comment by OlegDokuka** [comment]
It can have a sense. You may look at the new Loadbalance API for that purpose. Or implement your own pooling mechanism.

Also, once we have Aeron / QUIC implementations in place, it is going to be possible to utilize multiple threads to sends frames for those connection types.

Cheers,
Oleh

**Comment by KaimingWan** [comment]
@OlegDokuka I am not familiar with Aeron/QUIC. I find some doc about quic and know that it is based on udp protocol. Is it mean I can send parallel request to the single client if rsocket have quic implementation?

**Comment by OlegDokuka** [comment]
Yes.	Kind of. UDP allows frame 	reordering which in theory may be the result of independent frame delivery.

**Comment by KaimingWan** [comment]
@OlegDokuka Thanks for your replay and solve my question. I will have a try if rsocket implement Aeron/QUIC in the future.  The issue can be closed.

**Comment by KaimingWan** [comment]
@OlegDokuka Hi, I have another supplementary question. I cached my rsocket object when the rsocket client is started. Everytime I use the same rsocket object to send data. I use TcpClientTransport ot create my rsocket client(with cache). As we know, the netty using nio and can get result in a async way. I test my flowing code and find that If the previous rsocket request is blocked in server, the second request's result is blocked too. 

Is there some way in rsocket to get the async result over a single connection among multi threads? In my case, I don't care the order of response. Though the data is send in order over the single tcp connection,it is possible to read the data in a multi thread way. 

Server side acceptor code(Using spring rsocket style)
```java
    @MessageMapping("request-and-response-once")
    public Mono<ResponseData> requestAndResponseOnce(final String request) {
        log.info("Received fire-and-forget-once request: {}", request);
        return Mono.just(ResponseDataUtil.buildSuccess("success"));
    }

    @SneakyThrows
    @MessageMapping("request-and-response-block")
    public Mono<ResponseData> requestAndResponseBlock(final String request) {
        log.info("Received fire-and-forget-block request: {}", request);
        Thread.sleep(50000);
        return Mono.just(ResponseDataUtil.buildSuccess("success"));
    }
```

Client side sender code
```java

    @SneakyThrows
    @Test
    public void testParallelRequest() {
        Thread t1 = new Thread(() -> {
            sendHelloWorldBlockExample();
        });
        Thread t2 = new Thread(() -> {
            sendHelloWorldOnceExample();
        });
        log.warn("The first send request is executed....");
        t1.start();
        Thread.sleep(2000);
        log.warn("The second send request is executed....");
       //Can't get the result. I have to wait the first request finish the rtt.
        t2.start();
        Thread.sleep(Long.MAX_VALUE);
    }


    @SneakyThrows
    private void sendHelloWorldBlockExample() {
        RSocketRequester rsocketRequester = rSocketClient.getWorkingRequester();
        log.warn("begin send fire and forget block..........");
        rsocketRequester.route("request-and-response-block")
            .data("hello world")
            .retrieveMono(ResponseData.class)
            .subscribe();
    }

    @SneakyThrows
    private void sendHelloWorldOnceExample() {
        RSocketRequester rsocketRequester = rSocketClient.getWorkingRequester();
        log.warn("begin send request and response once..........");
        MonoFetcher monoFetcher = new DefaultMonoFetcher();
        rsocketRequester.route("request-and-response-once")
            .data("hello world")
            .retrieveMono(ResponseData.class)
            .subscribe(monoFetcher);

        log.warn("Result is " + monoFetcher.fetchResult().getData());
        Assert.assertEquals("success", monoFetcher.fetchResult().getData());
    }
```

MonoFetch to get the async result
```java
public class DefaultMonoFetcher implements MonoFetcher {

    // Unsafe mechanics
    private static final Unsafe UNSAFE;
    static {
        try {
            Field f = Unsafe.class.getDeclaredField("theUnsafe");
            f.setAccessible(true);
            UNSAFE = (Unsafe) f.get(null);
        } catch (Exception e) {
            String errMsg = "Get unsafe object failed with exception. Root cause is "
                            + ExceptionUtils.getRootCauseMessage(e);
            log.error(errMsg, e);
            throw new Error(e);
        }
    }
    private final int    BLOCKING_TIMEOUT_MS = 5000;
    private ResponseData responseData;
    private int          accepted            = 0;
    private long         acceptedValueOffset;
    /**
     * @return Fetched async result. The result may be null is there is no result
     */
    @SneakyThrows
    @Override
    public ResponseData fetchResult() {
        long startTimeMs = System.currentTimeMillis();
        Class<?> k = DefaultMonoFetcher.class;
        acceptedValueOffset = UNSAFE.objectFieldOffset(k.getDeclaredField("accepted"));

        while (true) {
            if (UNSAFE.compareAndSwapInt(this, acceptedValueOffset, 1, 2)) {
                return responseData;
            }
            if (System.currentTimeMillis() - startTimeMs > BLOCKING_TIMEOUT_MS) {
                return ResponseDataUtil
                    .buildError("Can't get async mono result after waiting for " + BLOCKING_TIMEOUT_MS + "ms");
            }
        }
    }

    @Override
    public void accept(Object responseData) {
        if (responseData != null && responseData instanceof ResponseData) {
            this.responseData = (ResponseData) responseData;
            accepted = 1;
        }
    }
}
```

**Comment by OlegDokuka** [comment]
Hi @KaimingWan!

The answer is - never block!
If you block - oflload it to another thread. If you block the Netty thread - all subsequent frames will be blocked as well.

Cheers
Oleh

**Comment by KaimingWan** [comment]
@OlegDokuka Do you mean not block thread in the server side？There may exists some case that code have bug and cause thread stuck. If the thread is stuck by some unknow reason, all the request over the single tcp connection will not receive any response. Am I right？

**Comment by OlegDokuka** [comment]
@KaimingWan that is correct. 

It is up to the user on how to manage such cases. RSocket only suggest to avoid blocking ops.

There is [BlockHound] (https://github.com/reactor/BlockHound) project which may help detecting any blocking ops in the production code.

Also, you may always write your own interceptor to offload all the calls on the separate scheduler (see the following link https://github.com/rsocket/rsocket-java/blob/master/rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/plugins/LimitRateInterceptorExample.java)

**Comment by KaimingWan** [comment]
@OlegDokuka Thanks for your solution. I will try them and give your response later.

**Comment by KaimingWan** [comment]
Hi @OlegDokuka , finaly I implement a dependent receiver component in the server side which hold a worker thread pool to do the biz for client's request and return the response in a async way. As you said, remove all blocking operations or operations that may cause blocking. Now I can send rsocket request parallely in the client (from the view of application layer) and get result from a future object async. Thanks for your advice.
