### ISSUE TITLE
Migration rsocket 1.0.0-RC6 to 1.0.2 breaks functionality

### ISSUE THREAD

**Issue by klopfdreh** [rsocket/rsocket-java#927]
## Expected Behavior
The implementation of 1.0.2 should work the same as 1.0.0-RC6

## Actual Behavior
When I start the ServerStarter and directly after that the ClientStarter - the publisher subscribes, but no request is sent to the server when subscriber.onComplete(); is called.

The client server roundtrip should work like before (master branch)

The changes I did to migrate from 1.0.0-RC6 to 1.0.2 can be viewed in https://github.com/klopfdreh/rsocket_playground/pull/3/files

## Steps to Reproduce
* Check out https://github.com/klopfdreh/rsocket_playground.git (rsocket_1_0_2 branch)
* Run ServerStarter
* Run ClientStarter

## Your Environment
See pom.xml rsocket-transport-netty 1.0.2 / rsocket-core 1.0.2

* RSocket version(s) used: 
1.0.2

* Other relevant libraries versions (eg. `netty`, ...):
netty

* Platform (eg. JVM version (`javar -version`) or Node version (`node --version`)): 
java 13.0.1 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

* OS and version (eg `uname -a`): 
macOS Catalina 10.15.6

**Comment by klopfdreh** [comment]
As of https://github.com/rsocket/rsocket-java/issues/628 with 1.0.0-RC6 the code was working.

**Comment by rstoyanchev** [comment]
@klopfdreh I think this is related to the use of a custom `Publisher` that is not respect back pressure and [publishes](https://github.com/klopfdreh/rsocket_playground/blob/458786e034f7e67735f7431d747f1ee6188512a6/src/main/java/de/klopfdreh/rsocket/playground/ClientController.java#L29) before demand. 

If I re-work that a bit to use a Flux:
```java
Flux<Payload> requestPayloads = Flux.fromIterable(persons).map(clientController::createClientPayload);
this.socket.requestChannel(requestPayloads)
        .doOnNext(payload -> log.info("Received payload from server: [{}]", payload.getDataUtf8()))
        // ...
```
where `createPayload` in `ClientController` is:
```java
    public Payload createClientPayload(Person person) {
        try {
            byte[] bytes = objectMapper.writeValueAsBytes(person);
            log.info("subscribe: [{}]", new String(bytes));
            return DefaultPayload.create(bytes);
        } catch (Exception e) {
            throw new IllegalStateException(e);
        }
    }
```

it works fine.

**Comment by klopfdreh** [comment]
Hey @rstoyanchev,

thanks a lot for the help here. My question regarding this would be, why this worked in 1.0.0-RC6. Was there a code rewriting that causes the change of behavior? 

The publisher is given as ClientController to the socket
```java
        ClientController clientController = new ClientController(persons);
        this.socket.requestChannel(Flux.from(clientController))
```

and as far as I understand should `subscriber.onNext` process the next payload. `subscriber.onComplete` then should cause the whole server roundtrip to be processed, finally.

I don't understand why to use the Subscriber anymore if I do it only with Flux.

**Comment by rstoyanchev** [comment]
@klopfdreh yes there were changes and even if the previous version was more lenient, the fact remains that your have a custom Publisher that does not behave according to Reactive Streams [rules for a Publisher](https://github.com/reactive-streams/reactive-streams-jvm#1-publisher-code) where a Publisher cannot call onNext before there is a request for more elements through the `Subscription` given to the `Subscriber`. Using a known well-behaved Publisher shows that it works as expected.

**Comment by klopfdreh** [comment]
Thanks a lot for clarification!

**Comment by klopfdreh** [comment]
@rstoyanchev The rewritten code works like a charm. I just wanted to know what exactly the issue was and as I read the documentation it is more clear to me. 👍

I guess this issue can be labeled as a question and I am going to close it with this comment.

The rework can be seen here:

https://github.com/klopfdreh/rsocket_playground/pull/3/commits/b8bf00c6d6666415fdfc46037ce0db17813d6846
