### ISSUE TITLE
Need a handler method in RSocket to receive a notification upon a successful connection 

### ISSUE THREAD

**Issue by vsaji** [rsocket/rsocket-java#965]
## Motivation
https://stackoverflow.com/questions/65304060/how-to-detect-if-rsocket-connection-is-successfull/65336056?noredirect=1#comment115542708_65336056

I'm unable to capture RSocket event that tells me the sever connection is successful. There are handlers for notifying connection drops and errors i.e doOnError, doOnTermination etc, why cannot we have method to notify a successful connection ? what is the limitation ? I had to implement a polling mechanism with Server on a regular interval to see if the connection is good. Which I think is not a clean solution. 

## Desired solution

Need a doOnSuccessfulConnection method in RSocket to notify the connection is established.

## Considered alternatives

 I had to implement a polling mechanism with Server on a regular interval to see if the connection is good. Which I think is not a clean solution.

**Comment by OlegDokuka** [comment]
Hi @vsaji!

RSocket-Java is built around Project Reactor and use Reactive Types offered by Project Reactor at all the places. 

For example, when you do `RSocketConnector.connectWith(someClientTransportHere)` you receive as a result a `Mono<RSocket>`.

Once you subscribe to `Mono<RSocket>` the underlying mechanism initiates a new connection to the specified peer and once the connection is opened, it sends a `SetupFrame` which provides all the information about the connector setup.

Once that happened, the `Subscriber` waiting for an `RSocket` instance is receiving `onNext(RSocket)` which might be considered as a signal about successful connection establishment.

If an error appears during the connection, the given `Mono` will end up with an `onError(Throwable)` signal providing the required info about the error.


**Please note**, RSocket uses [False Start](https://tools.ietf.org/html/draft-bmoeller-tls-falsestart-00#page-5) protocol for the handshake, which means RSocketConnector does not wait for any extra packets from the Server-side and may start sending requests upon Setup frame has been sent.

If you need a handshake mechanism, you are free to implement that via the `metadataPush` request

**Comment by vsaji** [comment]
Solution is updated here.
https://stackoverflow.com/questions/65304060/how-to-detect-if-rsocket-connection-is-successfull/65336056?noredirect=1#comment115542708_65336056
