### ISSUE TITLE
Add Codec for the Per Stream MIME Type Extension

### ISSUE THREAD

**Issue by rstoyanchev** [rsocket/rsocket-java#996]
There is currently no encoding and decoding support for the [PerStreamDataMimeTypesDefinition](https://github.com/rsocket/rsocket/blob/master/Extensions/PerStreamDataMimeTypesDefinition.md) extension.

**Comment by rudy2steiner** [comment]
I'll work on it

**Comment by rstoyanchev** [comment]
Superseded by #998.
